# Release configuration for dir-go client component
component: dir-go
package-name: dir-go
release-type: go
bump-minor-pre-major: true
bump-patch-for-minor-pre-major: true
draft: false
prerelease: false
include-v-in-tag: true
tag-separator: "/"

# Changelog configuration
changelog-sections:
  - type: feat
    section: Features
    hidden: false
  - type: fix
    section: Bug Fixes
    hidden: false
  - type: perf
    section: Performance Improvements
    hidden: false
  - type: docs
    section: Documentation
    hidden: false
  - type: refactor
    section: Code Refactoring
    hidden: false
  - type: build
    section: Build System
    hidden: false