// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: agntcy/dir/naming/v1/name_verification.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Verification represents the result of verifying a record's name ownership.
// It uses a oneof to support different verification types.
type Verification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Info:
	//
	//	*Verification_Domain
	Info          isVerification_Info `protobuf_oneof:"info"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verification) Reset() {
	*x = Verification{}
	mi := &file_agntcy_dir_naming_v1_name_verification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verification) ProtoMessage() {}

func (x *Verification) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_dir_naming_v1_name_verification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verification.ProtoReflect.Descriptor instead.
func (*Verification) Descriptor() ([]byte, []int) {
	return file_agntcy_dir_naming_v1_name_verification_proto_rawDescGZIP(), []int{0}
}

func (x *Verification) GetInfo() isVerification_Info {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Verification) GetDomain() *DomainVerification {
	if x != nil {
		if x, ok := x.Info.(*Verification_Domain); ok {
			return x.Domain
		}
	}
	return nil
}

type isVerification_Info interface {
	isVerification_Info()
}

type Verification_Domain struct {
	// Domain verification details.
	Domain *DomainVerification `protobuf:"bytes,1,opt,name=domain,proto3,oneof"` // Future verification types can be added here.
}

func (*Verification_Domain) isVerification_Info() {}

// DomainVerification represents the result of verifying that a record's
// signing key is authorized by the domain claimed in the record's name.
type DomainVerification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The domain that was verified (e.g., "cisco.com").
	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// The verification method used: "dns" or "wellknown".
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// The identifier of the domain's public key that matched the record's signing key.
	// This is the "id" field from the well-known file or derived from the DNS TXT record.
	KeyId string `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// When the verification was performed.
	VerifiedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainVerification) Reset() {
	*x = DomainVerification{}
	mi := &file_agntcy_dir_naming_v1_name_verification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainVerification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainVerification) ProtoMessage() {}

func (x *DomainVerification) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_dir_naming_v1_name_verification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainVerification.ProtoReflect.Descriptor instead.
func (*DomainVerification) Descriptor() ([]byte, []int) {
	return file_agntcy_dir_naming_v1_name_verification_proto_rawDescGZIP(), []int{1}
}

func (x *DomainVerification) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainVerification) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *DomainVerification) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *DomainVerification) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

var File_agntcy_dir_naming_v1_name_verification_proto protoreflect.FileDescriptor

var file_agntcy_dir_naming_v1_name_verification_proto_rawDesc = string([]byte{
	0x0a, 0x2c, 0x61, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2f, 0x64, 0x69, 0x72, 0x2f, 0x6e, 0x61, 0x6d,
	0x69, 0x6e, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14,
	0x61, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2e, 0x64, 0x69, 0x72, 0x2e, 0x6e, 0x61, 0x6d, 0x69, 0x6e,
	0x67, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x0c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x42, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x61, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2e, 0x64,
	0x69, 0x72, 0x2e, 0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x00, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x42, 0x06, 0x0a, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x22, 0x98, 0x01, 0x0a, 0x12, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6b, 0x65, 0x79, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6b, 0x65, 0x79, 0x49, 0x64, 0x12,
	0x3b, 0x0a, 0x0b, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x41, 0x74, 0x42, 0xc9, 0x01, 0x0a,
	0x18, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2e, 0x64, 0x69, 0x72, 0x2e,
	0x6e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x42, 0x15, 0x4e, 0x61, 0x6d, 0x65, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x67, 0x6e, 0x74, 0x63, 0x79, 0x2f, 0x64, 0x69, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x61,
	0x6d, 0x69, 0x6e, 0x67, 0x2f, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x41, 0x44, 0x4e, 0xaa, 0x02, 0x14,
	0x41, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2e, 0x44, 0x69, 0x72, 0x2e, 0x4e, 0x61, 0x6d, 0x69, 0x6e,
	0x67, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x14, 0x41, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x5c, 0x44, 0x69,
	0x72, 0x5c, 0x4e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x20, 0x41, 0x67,
	0x6e, 0x74, 0x63, 0x79, 0x5c, 0x44, 0x69, 0x72, 0x5c, 0x4e, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5c,
	0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x17, 0x41, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x3a, 0x3a, 0x44, 0x69, 0x72, 0x3a, 0x3a, 0x4e, 0x61,
	0x6d, 0x69, 0x6e, 0x67, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_agntcy_dir_naming_v1_name_verification_proto_rawDescOnce sync.Once
	file_agntcy_dir_naming_v1_name_verification_proto_rawDescData []byte
)

func file_agntcy_dir_naming_v1_name_verification_proto_rawDescGZIP() []byte {
	file_agntcy_dir_naming_v1_name_verification_proto_rawDescOnce.Do(func() {
		file_agntcy_dir_naming_v1_name_verification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agntcy_dir_naming_v1_name_verification_proto_rawDesc), len(file_agntcy_dir_naming_v1_name_verification_proto_rawDesc)))
	})
	return file_agntcy_dir_naming_v1_name_verification_proto_rawDescData
}

var file_agntcy_dir_naming_v1_name_verification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agntcy_dir_naming_v1_name_verification_proto_goTypes = []any{
	(*Verification)(nil),          // 0: agntcy.dir.naming.v1.Verification
	(*DomainVerification)(nil),    // 1: agntcy.dir.naming.v1.DomainVerification
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_agntcy_dir_naming_v1_name_verification_proto_depIdxs = []int32{
	1, // 0: agntcy.dir.naming.v1.Verification.domain:type_name -> agntcy.dir.naming.v1.DomainVerification
	2, // 1: agntcy.dir.naming.v1.DomainVerification.verified_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_agntcy_dir_naming_v1_name_verification_proto_init() }
func file_agntcy_dir_naming_v1_name_verification_proto_init() {
	if File_agntcy_dir_naming_v1_name_verification_proto != nil {
		return
	}
	file_agntcy_dir_naming_v1_name_verification_proto_msgTypes[0].OneofWrappers = []any{
		(*Verification_Domain)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agntcy_dir_naming_v1_name_verification_proto_rawDesc), len(file_agntcy_dir_naming_v1_name_verification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agntcy_dir_naming_v1_name_verification_proto_goTypes,
		DependencyIndexes: file_agntcy_dir_naming_v1_name_verification_proto_depIdxs,
		MessageInfos:      file_agntcy_dir_naming_v1_name_verification_proto_msgTypes,
	}.Build()
	File_agntcy_dir_naming_v1_name_verification_proto = out.File
	file_agntcy_dir_naming_v1_name_verification_proto_goTypes = nil
	file_agntcy_dir_naming_v1_name_verification_proto_depIdxs = nil
}
