# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from core.v1alpha2 import record_pb2 as core_dot_v1alpha2_dot_record__pb2
from store.v1alpha2 import object_pb2 as store_dot_v1alpha2_dot_object__pb2
from store.v1alpha2 import record_service_pb2 as store_dot_v1alpha2_dot_record__service__pb2


class RecordHandlerServiceStub(object):
    """Defines an interface for handling AgentRecord from stored object.
    This enables a consistent way to handle records irrespective of the
    the object type (e.g., different encodings or versions).
    This service must only be used on the client side.

    This interface tries to address two things:
    1. Enable compatibility between different types of 
    stored objects and latest AgentRecord schema.
    2. Ability to extract data from the object relevant for
    Directory APIs either in full or partial form
    (e.g., full AgentRecord or some form of a compact object).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConvertObjectToRecord = channel.unary_unary(
                '/store.v1alpha2.RecordHandlerService/ConvertObjectToRecord',
                request_serializer=store_dot_v1alpha2_dot_object__pb2.Object.SerializeToString,
                response_deserializer=core_dot_v1alpha2_dot_record__pb2.AgentRecord.FromString,
                _registered_method=True)
        self.ConvertRecordToObject = channel.unary_unary(
                '/store.v1alpha2.RecordHandlerService/ConvertRecordToObject',
                request_serializer=core_dot_v1alpha2_dot_record__pb2.AgentRecord.SerializeToString,
                response_deserializer=store_dot_v1alpha2_dot_object__pb2.Object.FromString,
                _registered_method=True)
        self.ValidateRecord = channel.unary_unary(
                '/store.v1alpha2.RecordHandlerService/ValidateRecord',
                request_serializer=core_dot_v1alpha2_dot_record__pb2.AgentRecord.SerializeToString,
                response_deserializer=store_dot_v1alpha2_dot_record__service__pb2.ValidateRecordResponse.FromString,
                _registered_method=True)


class RecordHandlerServiceServicer(object):
    """Defines an interface for handling AgentRecord from stored object.
    This enables a consistent way to handle records irrespective of the
    the object type (e.g., different encodings or versions).
    This service must only be used on the client side.

    This interface tries to address two things:
    1. Enable compatibility between different types of 
    stored objects and latest AgentRecord schema.
    2. Ability to extract data from the object relevant for
    Directory APIs either in full or partial form
    (e.g., full AgentRecord or some form of a compact object).
    """

    def ConvertObjectToRecord(self, request, context):
        """Converts a stored object to an AgentRecord.
        Supported objects can be any of AgentRecordObjectType.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertRecordToObject(self, request, context):
        """Converts an AgentRecord to a stored object.
        Returned object will have the lastest AgentRecordObjectType.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateRecord(self, request, context):
        """Validates the AgentRecord against the schema requirements.
        Throws an error if the record is invalid.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecordHandlerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConvertObjectToRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertObjectToRecord,
                    request_deserializer=store_dot_v1alpha2_dot_object__pb2.Object.FromString,
                    response_serializer=core_dot_v1alpha2_dot_record__pb2.AgentRecord.SerializeToString,
            ),
            'ConvertRecordToObject': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertRecordToObject,
                    request_deserializer=core_dot_v1alpha2_dot_record__pb2.AgentRecord.FromString,
                    response_serializer=store_dot_v1alpha2_dot_object__pb2.Object.SerializeToString,
            ),
            'ValidateRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateRecord,
                    request_deserializer=core_dot_v1alpha2_dot_record__pb2.AgentRecord.FromString,
                    response_serializer=store_dot_v1alpha2_dot_record__service__pb2.ValidateRecordResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'store.v1alpha2.RecordHandlerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('store.v1alpha2.RecordHandlerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecordHandlerService(object):
    """Defines an interface for handling AgentRecord from stored object.
    This enables a consistent way to handle records irrespective of the
    the object type (e.g., different encodings or versions).
    This service must only be used on the client side.

    This interface tries to address two things:
    1. Enable compatibility between different types of 
    stored objects and latest AgentRecord schema.
    2. Ability to extract data from the object relevant for
    Directory APIs either in full or partial form
    (e.g., full AgentRecord or some form of a compact object).
    """

    @staticmethod
    def ConvertObjectToRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/store.v1alpha2.RecordHandlerService/ConvertObjectToRecord',
            store_dot_v1alpha2_dot_object__pb2.Object.SerializeToString,
            core_dot_v1alpha2_dot_record__pb2.AgentRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConvertRecordToObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/store.v1alpha2.RecordHandlerService/ConvertRecordToObject',
            core_dot_v1alpha2_dot_record__pb2.AgentRecord.SerializeToString,
            store_dot_v1alpha2_dot_object__pb2.Object.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/store.v1alpha2.RecordHandlerService/ValidateRecord',
            core_dot_v1alpha2_dot_record__pb2.AgentRecord.SerializeToString,
            store_dot_v1alpha2_dot_record__service__pb2.ValidateRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
