approved = [
  "mit",
  "apache-2.0",
  "bsd-3-clause",
  "bsd-2-clause",
  "mpl-2.0",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "MIT",
  "OpenSSL",
  "CC0-1.0",
]

ignored = [
  "github.com/agntcy/dir/api",
  
  "google.golang.org/protobuf", # BSD-3-Clause
  "github.com/xi2/xz", # Public Domain https://github.com/xi2/xz/blob/master/LICENSE
  "github.com/libp2p/go-libp2p-gorpc", # MIT https://github.com/libp2p/go-libp2p-gorpc/blob/master/LICENSE-MIT
  "go.mongodb.org/mongo-driver" # Apache License 2.0 https://github.com/mongodb/mongo-go-driver/blob/master/LICENSE
]