codecov:
  require_ci_to_pass: false

comment:
  require_changes: false

coverage:
  precision: 1
  round: nearest
  range: 40..90
  status:
    project:
      default:
        target: auto
        threshold: 2%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
    changes: false

ignore:
  - "**/*.pb.go"
  - "**/mock_*.go"
  - "tests/**"
  - "**/testdata/**"
