// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/core/v1/record.proto (package agntcy.dir.core.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file agntcy/dir/core/v1/record.proto.
 */
export declare const file_agntcy_dir_core_v1_record: GenFile;

/**
 * Defines a reference or a globally unique content identifier of a record.
 *
 * @generated from message agntcy.dir.core.v1.RecordRef
 */
export declare type RecordRef = Message<"agntcy.dir.core.v1.RecordRef"> & {
  /**
   * Globally-unique content identifier (CID) of the record.
   * Specs: https://github.com/multiformats/cid
   *
   * @generated from field: string cid = 1;
   */
  cid: string;
};

/**
 * Describes the message agntcy.dir.core.v1.RecordRef.
 * Use `create(RecordRefSchema)` to create a new message.
 */
export declare const RecordRefSchema: GenMessage<RecordRef>;

/**
 * Defines a Record stored in the system.
 *
 * @generated from message agntcy.dir.core.v1.RecordMeta
 */
export declare type RecordMeta = Message<"agntcy.dir.core.v1.RecordMeta"> & {
  /**
   * CID of this object.
   *
   * @generated from field: string cid = 1;
   */
  cid: string;

  /**
   * Annotations attached to the record.
   *
   * @generated from field: map<string, string> annotations = 2;
   */
  annotations: { [key: string]: string };

  /**
   * Creation timestamp of the record in the RFC3339 format.
   * Specs: https://www.rfc-editor.org/rfc/rfc3339.html
   *
   * @generated from field: string created_at = 3;
   */
  createdAt: string;

  /**
   * The type of the object.
   * For example, "agntcy.dir.sign.v1.Signature" for signatures.
   *
   * @generated from field: string type = 4;
   */
  type: string;

  /**
   * Links to other records.
   *
   * @generated from field: repeated agntcy.dir.core.v1.RecordRef links = 5;
   */
  links: RecordRef[];

  /**
   * Parent record reference, if any.
   *
   * @generated from field: optional agntcy.dir.core.v1.RecordRef parent = 6;
   */
  parent?: RecordRef;

  /**
   * Size of the record data in bytes.
   *
   * @generated from field: uint64 size = 7;
   */
  size: bigint;
};

/**
 * Describes the message agntcy.dir.core.v1.RecordMeta.
 * Use `create(RecordMetaSchema)` to create a new message.
 */
export declare const RecordMetaSchema: GenMessage<RecordMeta>;

/**
 * @generated from message agntcy.dir.core.v1.Record
 */
export declare type Record = Message<"agntcy.dir.core.v1.Record"> & {
  /**
   * @generated from field: optional agntcy.dir.core.v1.RecordMeta meta = 1;
   */
  meta?: RecordMeta;

  /**
   * The actual data of the record.
   * Supported schemas:
   *
   * 0.3.1: https://schema.oasf.outshift.com/0.3.1/objects/agent
   * 0.7.0: https://schema.oasf.outshift.com/0.7.0/objects/record
   *
   * @generated from field: google.protobuf.Struct data = 2;
   */
  data?: JsonObject;
};

/**
 * Describes the message agntcy.dir.core.v1.Record.
 * Use `create(RecordSchema)` to create a new message.
 */
export declare const RecordSchema: GenMessage<Record>;

