// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/core/v1/referrer.proto (package agntcy.dir.core.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file agntcy/dir/core/v1/referrer.proto.
 */
export declare const file_agntcy_dir_core_v1_referrer: GenFile;

/**
 * @generated from message agntcy.dir.core.v1.ReferrerRef
 */
export declare type ReferrerRef = Message<"agntcy.dir.core.v1.ReferrerRef"> & {
  /**
   * Content Identifier (https://github.com/multiformats/cid)
   * A self-describing, content-addressed identifier
   *
   * @generated from field: string cid = 1;
   */
  cid: string;
};

/**
 * Describes the message agntcy.dir.core.v1.ReferrerRef.
 * Use `create(ReferrerRefSchema)` to create a new message.
 */
export declare const ReferrerRefSchema: GenMessage<ReferrerRef>;

