// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/core/v1/rules.proto (package agntcy.dir.core.v1, syntax proto2)
/* eslint-disable */

import { extDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb.js";

/**
 * Describes the file agntcy/dir/core/v1/rules.proto.
 */
export const file_agntcy_dir_core_v1_rules = /*@__PURE__*/
  fileDesc("Ch5hZ250Y3kvZGlyL2NvcmUvdjEvcnVsZXMucHJvdG8SEmFnbnRjeS5kaXIuY29yZS52MTrXAQoQaXNfcmVmZXJyZXJfdHlwZRIZLmJ1Zi52YWxpZGF0ZS5TdHJpbmdSdWxlcxjQhgMgASgIQo8BwkiLAQqIAQoXc3RyaW5nLmlzX3JlZmVycmVyX3R5cGUSI3ZhbHVlIG11c3QgYmUgYSB2YWxpZCByZWZlcnJlciB0eXBlGkh0aGlzIGluIFsnYWdudGN5LmRpci5zaWduLnYxLlB1YmxpY0tleScsICdhZ250Y3kuZGlyLnNpZ24udjEuU2lnbmF0dXJlJ11SDmlzUmVmZXJyZXJUeXBlOosBCgZpc19jaWQSGS5idWYudmFsaWRhdGUuU3RyaW5nUnVsZXMY0YYDIAEoCEJXwkhUClIKDXN0cmluZy5pc19jaWQSGXZhbHVlIG11c3QgYmUgYSB2YWxpZCBDSUQaJjEgPD0gdGhpcy5zaXplKCkgJiYgdGhpcy5zaXplKCkgPD0gMTI4UgVpc0NpZEKyAQoWY29tLmFnbnRjeS5kaXIuY29yZS52MUIKUnVsZXNQcm90b1ABWiFnaXRodWIuY29tL2FnbnRjeS9kaXIvYXBpL2NvcmUvdjGiAgNBREOqAhJBZ250Y3kuRGlyLkNvcmUuVjHKAhJBZ250Y3lcRGlyXENvcmVcVjHiAh5BZ250Y3lcRGlyXENvcmVcVjFcR1BCTWV0YWRhdGHqAhVBZ250Y3k6OkRpcjo6Q29yZTo6VjE", [file_buf_validate_validate]);

/**
 * @generated from extension: optional bool is_referrer_type = 50000;
 */
export const is_referrer_type = /*@__PURE__*/
  extDesc(file_agntcy_dir_core_v1_rules, 0);

/**
 * @generated from extension: optional bool is_cid = 50001;
 */
export const is_cid = /*@__PURE__*/
  extDesc(file_agntcy_dir_core_v1_rules, 1);

