// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: agntcy/dir/store/v2/objstore_service.proto

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ObjectStore_Put_FullMethodName           = "/agntcy.dir.store.v2.ObjectStore/Put"
	ObjectStore_Get_FullMethodName           = "/agntcy.dir.store.v2.ObjectStore/Get"
	ObjectStore_GetRaw_FullMethodName        = "/agntcy.dir.store.v2.ObjectStore/GetRaw"
	ObjectStore_Has_FullMethodName           = "/agntcy.dir.store.v2.ObjectStore/Has"
	ObjectStore_Delete_FullMethodName        = "/agntcy.dir.store.v2.ObjectStore/Delete"
	ObjectStore_Lookup_FullMethodName        = "/agntcy.dir.store.v2.ObjectStore/Lookup"
	ObjectStore_ListReferrers_FullMethodName = "/agntcy.dir.store.v2.ObjectStore/ListReferrers"
)

// ObjectStoreClient is the client API for ObjectStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ObjectStore provides APIs for managing objects in a content-addressable store.
//
// It is a thin wrapper around the OCI Distribution Spec that performs content
// validation and normalization for certain media types.
//
// Supported media types:
// - application/octet-stream
// - application/vnd.oci.image.manifest.v1+json
// - application/vnd.agntcy.dir.objects.referrer+json
// - application/vnd.agntcy.dir.objects.record+json
type ObjectStoreClient interface {
	// Writes the object to the store and returns its descriptor.
	//
	// Put may perform content validation/normalization, and return the
	// canonical descriptor of the stored object.
	Put(ctx context.Context, in *Object, opts ...grpc.CallOption) (*ObjectDescriptor, error)
	// Returns the object data for the given reference.
	Get(ctx context.Context, in *ObjectRef, opts ...grpc.CallOption) (*Object, error)
	// Returns the raw object data for the given reference without any content validation/normalization.
	// For example, if the object is an OCI image manifest, GetRaw will return the original manifest data
	// as stored in the registry.
	GetRaw(ctx context.Context, in *ObjectRef, opts ...grpc.CallOption) (*Object, error)
	// Returns true if the object exists in the store.
	Has(ctx context.Context, in *ObjectRef, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error)
	// Deletes the object from the store. Returns an error if the object does not exist.
	Delete(ctx context.Context, in *ObjectRef, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Indexing details, returns metadata of the object without retrieving
	// the actual data.
	Lookup(ctx context.Context, in *ObjectRef, opts ...grpc.CallOption) (*ObjectDescriptor, error)
	// Linkage details, returns objects that reference this object.
	ListReferrers(ctx context.Context, in *ListReferrersRequest, opts ...grpc.CallOption) (*ListReferrersResponse, error)
}

type objectStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewObjectStoreClient(cc grpc.ClientConnInterface) ObjectStoreClient {
	return &objectStoreClient{cc}
}

func (c *objectStoreClient) Put(ctx context.Context, in *Object, opts ...grpc.CallOption) (*ObjectDescriptor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectDescriptor)
	err := c.cc.Invoke(ctx, ObjectStore_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) Get(ctx context.Context, in *ObjectRef, opts ...grpc.CallOption) (*Object, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Object)
	err := c.cc.Invoke(ctx, ObjectStore_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) GetRaw(ctx context.Context, in *ObjectRef, opts ...grpc.CallOption) (*Object, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Object)
	err := c.cc.Invoke(ctx, ObjectStore_GetRaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) Has(ctx context.Context, in *ObjectRef, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrapperspb.BoolValue)
	err := c.cc.Invoke(ctx, ObjectStore_Has_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) Delete(ctx context.Context, in *ObjectRef, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ObjectStore_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) Lookup(ctx context.Context, in *ObjectRef, opts ...grpc.CallOption) (*ObjectDescriptor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectDescriptor)
	err := c.cc.Invoke(ctx, ObjectStore_Lookup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) ListReferrers(ctx context.Context, in *ListReferrersRequest, opts ...grpc.CallOption) (*ListReferrersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReferrersResponse)
	err := c.cc.Invoke(ctx, ObjectStore_ListReferrers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObjectStoreServer is the server API for ObjectStore service.
// All implementations should embed UnimplementedObjectStoreServer
// for forward compatibility.
//
// ObjectStore provides APIs for managing objects in a content-addressable store.
//
// It is a thin wrapper around the OCI Distribution Spec that performs content
// validation and normalization for certain media types.
//
// Supported media types:
// - application/octet-stream
// - application/vnd.oci.image.manifest.v1+json
// - application/vnd.agntcy.dir.objects.referrer+json
// - application/vnd.agntcy.dir.objects.record+json
type ObjectStoreServer interface {
	// Writes the object to the store and returns its descriptor.
	//
	// Put may perform content validation/normalization, and return the
	// canonical descriptor of the stored object.
	Put(context.Context, *Object) (*ObjectDescriptor, error)
	// Returns the object data for the given reference.
	Get(context.Context, *ObjectRef) (*Object, error)
	// Returns the raw object data for the given reference without any content validation/normalization.
	// For example, if the object is an OCI image manifest, GetRaw will return the original manifest data
	// as stored in the registry.
	GetRaw(context.Context, *ObjectRef) (*Object, error)
	// Returns true if the object exists in the store.
	Has(context.Context, *ObjectRef) (*wrapperspb.BoolValue, error)
	// Deletes the object from the store. Returns an error if the object does not exist.
	Delete(context.Context, *ObjectRef) (*emptypb.Empty, error)
	// Indexing details, returns metadata of the object without retrieving
	// the actual data.
	Lookup(context.Context, *ObjectRef) (*ObjectDescriptor, error)
	// Linkage details, returns objects that reference this object.
	ListReferrers(context.Context, *ListReferrersRequest) (*ListReferrersResponse, error)
}

// UnimplementedObjectStoreServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedObjectStoreServer struct{}

func (UnimplementedObjectStoreServer) Put(context.Context, *Object) (*ObjectDescriptor, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedObjectStoreServer) Get(context.Context, *ObjectRef) (*Object, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedObjectStoreServer) GetRaw(context.Context, *ObjectRef) (*Object, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRaw not implemented")
}
func (UnimplementedObjectStoreServer) Has(context.Context, *ObjectRef) (*wrapperspb.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Has not implemented")
}
func (UnimplementedObjectStoreServer) Delete(context.Context, *ObjectRef) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedObjectStoreServer) Lookup(context.Context, *ObjectRef) (*ObjectDescriptor, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lookup not implemented")
}
func (UnimplementedObjectStoreServer) ListReferrers(context.Context, *ListReferrersRequest) (*ListReferrersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReferrers not implemented")
}
func (UnimplementedObjectStoreServer) testEmbeddedByValue() {}

// UnsafeObjectStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObjectStoreServer will
// result in compilation errors.
type UnsafeObjectStoreServer interface {
	mustEmbedUnimplementedObjectStoreServer()
}

func RegisterObjectStoreServer(s grpc.ServiceRegistrar, srv ObjectStoreServer) {
	// If the following call pancis, it indicates UnimplementedObjectStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ObjectStore_ServiceDesc, srv)
}

func _ObjectStore_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Object)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).Put(ctx, req.(*Object))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).Get(ctx, req.(*ObjectRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_GetRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).GetRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_GetRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).GetRaw(ctx, req.(*ObjectRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_Has_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).Has(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_Has_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).Has(ctx, req.(*ObjectRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).Delete(ctx, req.(*ObjectRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_Lookup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).Lookup(ctx, req.(*ObjectRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_ListReferrers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReferrersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).ListReferrers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_ListReferrers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).ListReferrers(ctx, req.(*ListReferrersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ObjectStore_ServiceDesc is the grpc.ServiceDesc for ObjectStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObjectStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agntcy.dir.store.v2.ObjectStore",
	HandlerType: (*ObjectStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _ObjectStore_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ObjectStore_Get_Handler,
		},
		{
			MethodName: "GetRaw",
			Handler:    _ObjectStore_GetRaw_Handler,
		},
		{
			MethodName: "Has",
			Handler:    _ObjectStore_Has_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ObjectStore_Delete_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _ObjectStore_Lookup_Handler,
		},
		{
			MethodName: "ListReferrers",
			Handler:    _ObjectStore_ListReferrers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agntcy/dir/store/v2/objstore_service.proto",
}
