# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: "3"

tasks:
  runtime:gen:
    desc: Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations
    dir: ./api
    deps:
      - deps:controller-gen
    cmds:
      - go run {{ .CONTROLLER_GEN_BIN }} object paths=./crd/v1/...
      - go run {{ .CONTROLLER_GEN_BIN }} crd:ignoreUnexportedFields=true object:headerFile="./crd/v1/boilerplate.go.txt" paths="./crd/v1/..." output:crd:artifacts:config="../install/chart/templates"
