# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from agntcy.dir.store.v1 import object_pb2 as agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class StoreServiceStub(object):
    """Defines an interface for content-addressable storage
    service for arbitrary objects.
    Supports DAG structure creation via object linking.

    Objects are mapped to OCI artifacts, and stored in OCI-compliant
    format.
    The object references map OCI digest to CIDs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Push = channel.stream_unary(
                '/agntcy.dir.store.v1.StoreService/Push',
                request_serializer=agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.Object.SerializeToString,
                response_deserializer=agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectRef.FromString,
                _registered_method=True)
        self.Pull = channel.unary_stream(
                '/agntcy.dir.store.v1.StoreService/Pull',
                request_serializer=agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectRef.SerializeToString,
                response_deserializer=agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.Object.FromString,
                _registered_method=True)
        self.Lookup = channel.unary_unary(
                '/agntcy.dir.store.v1.StoreService/Lookup',
                request_serializer=agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectRef.SerializeToString,
                response_deserializer=agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectMeta.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/agntcy.dir.store.v1.StoreService/Delete',
                request_serializer=agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectRef.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Walk = channel.unary_stream(
                '/agntcy.dir.store.v1.StoreService/Walk',
                request_serializer=agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectRef.SerializeToString,
                response_deserializer=agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectMeta.FromString,
                _registered_method=True)
        self.ListReferrers = channel.unary_stream(
                '/agntcy.dir.store.v1.StoreService/ListReferrers',
                request_serializer=agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectRef.SerializeToString,
                response_deserializer=agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectMeta.FromString,
                _registered_method=True)


class StoreServiceServicer(object):
    """Defines an interface for content-addressable storage
    service for arbitrary objects.
    Supports DAG structure creation via object linking.

    Objects are mapped to OCI artifacts, and stored in OCI-compliant
    format.
    The object references map OCI digest to CIDs.
    """

    def Push(self, request_iterator, context):
        """Push performs write operation for a given object.
        Data is streamed in chunks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pull(self, request, context):
        """Pull performs read operation for a given object.
        Data is streamed in chunks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lookup(self, request, context):
        """Lookup resolves basic metadata for a given object.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Remove performs delete operation for a given object.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Walk(self, request, context):
        """Walk lists all linked objects starting from the given root objects.
        Use Pull to retrieve actual data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReferrers(self, request, context):
        """ListReferrers lists all objects that reference the given object.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Push': grpc.stream_unary_rpc_method_handler(
                    servicer.Push,
                    request_deserializer=agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.Object.FromString,
                    response_serializer=agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectRef.SerializeToString,
            ),
            'Pull': grpc.unary_stream_rpc_method_handler(
                    servicer.Pull,
                    request_deserializer=agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectRef.FromString,
                    response_serializer=agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.Object.SerializeToString,
            ),
            'Lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.Lookup,
                    request_deserializer=agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectRef.FromString,
                    response_serializer=agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectMeta.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectRef.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Walk': grpc.unary_stream_rpc_method_handler(
                    servicer.Walk,
                    request_deserializer=agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectRef.FromString,
                    response_serializer=agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectMeta.SerializeToString,
            ),
            'ListReferrers': grpc.unary_stream_rpc_method_handler(
                    servicer.ListReferrers,
                    request_deserializer=agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectRef.FromString,
                    response_serializer=agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectMeta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agntcy.dir.store.v1.StoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agntcy.dir.store.v1.StoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StoreService(object):
    """Defines an interface for content-addressable storage
    service for arbitrary objects.
    Supports DAG structure creation via object linking.

    Objects are mapped to OCI artifacts, and stored in OCI-compliant
    format.
    The object references map OCI digest to CIDs.
    """

    @staticmethod
    def Push(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/agntcy.dir.store.v1.StoreService/Push',
            agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.Object.SerializeToString,
            agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectRef.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pull(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agntcy.dir.store.v1.StoreService/Pull',
            agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectRef.SerializeToString,
            agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.Object.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agntcy.dir.store.v1.StoreService/Lookup',
            agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectRef.SerializeToString,
            agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectMeta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agntcy.dir.store.v1.StoreService/Delete',
            agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectRef.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Walk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agntcy.dir.store.v1.StoreService/Walk',
            agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectRef.SerializeToString,
            agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectMeta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReferrers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agntcy.dir.store.v1.StoreService/ListReferrers',
            agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectRef.SerializeToString,
            agntcy_dot_dir_dot_store_dot_v1_dot_object__pb2.ObjectMeta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
