# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: discovery
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: discovery
rules:
  # Runtime discovery permissions
  - apiGroups: [""]
    resources: ["pods", "services", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch"]
  # CRD permissions (for writer)
  - apiGroups: ["discovery.agntcy.io"]
    resources: ["discoveredworkloads"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: discovery
subjects:
  - kind: ServiceAccount
    name: discovery
    namespace: default
roleRef:
  kind: ClusterRole
  name: discovery
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
  template:
    metadata:
      labels:
        app: discovery
        role: inspector
    spec:
      serviceAccountName: discovery
      containers:
        - name: discovery
          image: discovery:latest
          imagePullPolicy: Never
          env:
            # Storage - CRD
            - name: DISCOVERY_STORE_TYPE
              value: "crd"
            - name: DISCOVERY_STORE_CRD_NAMESPACE
              value: "default"
            # Runtime - Kubernetes
            - name: DISCOVERY_RUNTIME_TYPE
              value: "kubernetes"
            # Resolvers
            - name: DISCOVERY_RESOLVER_A2A_ENABLED
              value: "true"
            - name: DISCOVERY_RESOLVER_OASF_ENABLED
              value: "true"
            - name: DISCOVERY_WORKERS
              value: "16"
            # Directory client config
            - name: DIRECTORY_CLIENT_SERVER_ADDRESS
              value: "apiserver:8888"
            - name: DIRECTORY_CLIENT_AUTH_MODE
              value: "insecure"
# ============================================================================
# SERVER (reads from CRDs)
# ============================================================================
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: discovery-server
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: discovery-server
rules:
  # CRD permissions (read-only for server)
  - apiGroups: ["discovery.agntcy.io"]
    resources: ["discoveredworkloads"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: discovery-server
subjects:
  - kind: ServiceAccount
    name: discovery-server
    namespace: default
roleRef:
  kind: ClusterRole
  name: discovery-server
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: discovery-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      serviceAccountName: discovery-server
      containers:
        - name: server
          image: discovery-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            # Storage - CRD
            - name: SERVER_STORE_TYPE
              value: "crd"
            - name: SERVER_STORE_CRD_GROUP
              value: "discovery.agntcy.io"
            - name: SERVER_STORE_CRD_VERSION
              value: "v1"
            - name: SERVER_STORE_CRD_RESOURCE
              value: "discoveredworkloads"
            - name: SERVER_STORE_CRD_NAMESPACE
              value: "default"
            - name: SERVER_STORE_CRD_IN_CLUSTER
              value: "true"
            # Server
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "8080"
# ============================================================================
# TEST WORKLOADS (namespaces act as isolation groups)
# ============================================================================
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-a
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-b
---
apiVersion: v1
kind: Service
metadata:
  name: svc-1
  namespace: team-a
spec:
  selector:
    app: service-1
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-3
  namespace: team-a
spec:
  selector:
    app: service-3
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-2
  namespace: team-b
spec:
  selector:
    app: service-2
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-4
  namespace: team-b
spec:
  selector:
    app: service-4
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: service-1
  namespace: team-a
  labels:
    org.agntcy/discover: "true"
    app: service-1
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: service-a2a
  namespace: team-a
  labels:
    app: service-a2a
    org.agntcy/discover: "true"
    org.agntcy/agent-type: "a2a"
    ## TODO: DNS names are not yet supported in k8s manifest labels
    # org.agntcy/agent-record: "dns-validation-http/example/research-assistant-v4:v4.0.0"
spec:
  containers:
    - name: a2a-helloworld
      image: ghcr.io/ramizpolic/a2a-helloworld:latest
      ports:
        - containerPort: 8080
        - containerPort: 9999
---
apiVersion: v1
kind: Pod
metadata:
  name: service-3
  namespace: team-a
  labels:
    org.agntcy/discover: "true"
    app: service-3
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: service-2
  namespace: team-b
  labels:
    org.agntcy/discover: "true"
    app: service-2
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: service-4
  namespace: team-b
  labels:
    org.agntcy/discover: "true"
    app: service-4
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
# ============================================================================
# NETWORK POLICIES
# ============================================================================
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-inspector-ingress
  namespace: team-a
spec:
  podSelector:
    matchLabels:
      org.agntcy/discover: "true"
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: default
          podSelector:
            matchLabels:
              role: inspector
      ports:
        - protocol: TCP
          port: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-inspector-ingress
  namespace: team-b
spec:
  podSelector:
    matchLabels:
      org.agntcy/discover: "true"
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: default
          podSelector:
            matchLabels:
              role: inspector
      ports:
        - protocol: TCP
          port: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: team-a
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
