# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: "3"

tasks:
  default:
    cmd: echo "Run the main Taskfile instead of this one."

  gui:build:macos:
    desc: Build the GUI for macOS
    dir: gui
    cmds:
      - flutter config --enable-macos-desktop
      - flutter create . --platforms=macos
      - flutter build macos
