# Release configuration for dirctl component
component: dirctl
package-name: dirctl
release-type: go
bump-minor-pre-major: true
bump-patch-for-minor-pre-major: true
draft: false
prerelease: false
include-v-in-tag: true
tag-separator: "/"

# Additional files to update on release
extra-files:
  - type: yaml
    path: install/charts/dirctl/Chart.yaml
    jsonpath: $.version
  - type: yaml
    path: install/charts/dirctl/Chart.yaml
    jsonpath: $.appVersion

# Changelog configuration
changelog-sections:
  - type: feat
    section: Features
    hidden: false
  - type: fix
    section: Bug Fixes
    hidden: false
  - type: perf
    section: Performance Improvements
    hidden: false
  - type: docs
    section: Documentation
    hidden: false
  - type: refactor
    section: Code Refactoring
    hidden: false
  - type: build
    section: Build System
    hidden: false