builder:
  # Base agent model path.
  # Path is either absolute or relative to this build config file.
  base-model: "agent.base.json"

  # List of paths to ignore
  source-ignore:
    - ".venv/"

  # Enable or disable the LLMAnalyzer plugin
  llmanalyzer: false

  # Enable or disable the runtime plugin
  runtime: false
