# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: Bug Report
description: Report a bug to help us improve.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Please provide a description of the problem
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Please describe what you expected would happen
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Affected Version
      description: |
        Please specify the version where this issue was encountered.
        Common versions: v0.3.0, v0.2.13, main (development)
        You can find all releases at: https://github.com/agntcy/dir/releases
      placeholder: "e.g., v0.3.0 or main"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please provide all steps to reproduce the behavior
      placeholder: |
        1. In this environment...
        1. With this config...
        1. Run `this command`...
        1. See error...
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: By submitting this issue, you agree to the following
      options:
        - label: I have read the [contributing guidelines](/agntcy/repo-template/blob/main/CONTRIBUTING.md)
          required: true
        - label: I have verified this does not duplicate an existing issue
          required: true
