// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/runtime/v1/discovery_service.proto (package agntcy.dir.runtime.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_agntcy_dir_runtime_v1_process } from "./process_pb.js";

/**
 * Describes the file agntcy/dir/runtime/v1/discovery_service.proto.
 */
export const file_agntcy_dir_runtime_v1_discovery_service = /*@__PURE__*/
  fileDesc("Ci1hZ250Y3kvZGlyL3J1bnRpbWUvdjEvZGlzY292ZXJ5X3NlcnZpY2UucHJvdG8SFWFnbnRjeS5kaXIucnVudGltZS52MSInChRMaXN0UHJvY2Vzc2VzUmVxdWVzdBIPCgdmaWx0ZXJzGAEgAygJMnIKEERpc2NvdmVyeVNlcnZpY2USXgoNTGlzdFByb2Nlc3NlcxIrLmFnbnRjeS5kaXIucnVudGltZS52MS5MaXN0UHJvY2Vzc2VzUmVxdWVzdBoeLmFnbnRjeS5kaXIucnVudGltZS52MS5Qcm9jZXNzMAFCzwEKGWNvbS5hZ250Y3kuZGlyLnJ1bnRpbWUudjFCFURpc2NvdmVyeVNlcnZpY2VQcm90b1ABWiRnaXRodWIuY29tL2FnbnRjeS9kaXIvYXBpL3J1bnRpbWUvdjGiAgNBRFKqAhVBZ250Y3kuRGlyLlJ1bnRpbWUuVjHKAhVBZ250Y3lcRGlyXFJ1bnRpbWVcVjHiAiFBZ250Y3lcRGlyXFJ1bnRpbWVcVjFcR1BCTWV0YWRhdGHqAhhBZ250Y3k6OkRpcjo6UnVudGltZTo6VjFiBnByb3RvMw", [file_agntcy_dir_runtime_v1_process]);

/**
 * Describes the message agntcy.dir.runtime.v1.ListProcessesRequest.
 * Use `create(ListProcessesRequestSchema)` to create a new message.
 */
export const ListProcessesRequestSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_runtime_v1_discovery_service, 0);

/**
 * @generated from service agntcy.dir.runtime.v1.DiscoveryService
 */
export const DiscoveryService = /*@__PURE__*/
  serviceDesc(file_agntcy_dir_runtime_v1_discovery_service, 0);

