// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/runtime/v1/process.proto (package agntcy.dir.runtime.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { RecordMeta } from "../../core/v1/record_pb.js";

/**
 * Describes the file agntcy/dir/runtime/v1/process.proto.
 */
export declare const file_agntcy_dir_runtime_v1_process: GenFile;

/**
 * Information about a agent process instance.
 *
 * @generated from message agntcy.dir.runtime.v1.Process
 */
export declare type Process = Message<"agntcy.dir.runtime.v1.Process"> & {
  /**
   * Process ID
   *
   * @generated from field: string pid = 1;
   */
  pid: string;

  /**
   * Name of the runtime environment
   *
   * @generated from field: string runtime = 2;
   */
  runtime: string;

  /**
   * Process creation timestamp in the RFC3339 format.
   *
   * @generated from field: string created_at = 3;
   */
  createdAt: string;

  /**
   * Process metadata
   *
   * @generated from field: map<string, string> annotations = 4;
   */
  annotations: { [key: string]: string };

  /**
   * The record from which this process was created.
   *
   * @generated from field: agntcy.dir.core.v1.RecordMeta record = 5;
   */
  record?: RecordMeta;
};

/**
 * Describes the message agntcy.dir.runtime.v1.Process.
 * Use `create(ProcessSchema)` to create a new message.
 */
export declare const ProcessSchema: GenMessage<Process>;

