// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/runtime/v1/runtime_service.proto (package agntcy.dir.runtime.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_agntcy_dir_runtime_v1_process } from "./process_pb.js";

/**
 * Describes the file agntcy/dir/runtime/v1/runtime_service.proto.
 */
export const file_agntcy_dir_runtime_v1_runtime_service = /*@__PURE__*/
  fileDesc("CithZ250Y3kvZGlyL3J1bnRpbWUvdjEvcnVudGltZV9zZXJ2aWNlLnByb3RvEhVhZ250Y3kuZGlyLnJ1bnRpbWUudjEiJwoUTGlzdFByb2Nlc3Nlc1JlcXVlc3QSDwoHZmlsdGVycxgBIAMoCTJwCg5SdW50aW1lU2VydmljZRJeCg1MaXN0UHJvY2Vzc2VzEisuYWdudGN5LmRpci5ydW50aW1lLnYxLkxpc3RQcm9jZXNzZXNSZXF1ZXN0Gh4uYWdudGN5LmRpci5ydW50aW1lLnYxLlByb2Nlc3MwAULNAQoZY29tLmFnbnRjeS5kaXIucnVudGltZS52MUITUnVudGltZVNlcnZpY2VQcm90b1ABWiRnaXRodWIuY29tL2FnbnRjeS9kaXIvYXBpL3J1bnRpbWUvdjGiAgNBRFKqAhVBZ250Y3kuRGlyLlJ1bnRpbWUuVjHKAhVBZ250Y3lcRGlyXFJ1bnRpbWVcVjHiAiFBZ250Y3lcRGlyXFJ1bnRpbWVcVjFcR1BCTWV0YWRhdGHqAhhBZ250Y3k6OkRpcjo6UnVudGltZTo6VjFiBnByb3RvMw", [file_agntcy_dir_runtime_v1_process]);

/**
 * Describes the message agntcy.dir.runtime.v1.ListProcessesRequest.
 * Use `create(ListProcessesRequestSchema)` to create a new message.
 */
export const ListProcessesRequestSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_runtime_v1_runtime_service, 0);

/**
 * @generated from service agntcy.dir.runtime.v1.RuntimeService
 */
export const RuntimeService = /*@__PURE__*/
  serviceDesc(file_agntcy_dir_runtime_v1_runtime_service, 0);

