// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/runtime/v1/runtime_service.proto (package agntcy.dir.runtime.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { ProcessSchema } from "./process_pb.js";

/**
 * Describes the file agntcy/dir/runtime/v1/runtime_service.proto.
 */
export declare const file_agntcy_dir_runtime_v1_runtime_service: GenFile;

/**
 * @generated from message agntcy.dir.runtime.v1.ListProcessesRequest
 */
export declare type ListProcessesRequest = Message<"agntcy.dir.runtime.v1.ListProcessesRequest"> & {
  /**
   * Filters to apply when listing processes.
   * Accepts regexp pattern if single value is provided.
   *
   * @generated from field: repeated string filters = 1;
   */
  filters: string[];
};

/**
 * Describes the message agntcy.dir.runtime.v1.ListProcessesRequest.
 * Use `create(ListProcessesRequestSchema)` to create a new message.
 */
export declare const ListProcessesRequestSchema: GenMessage<ListProcessesRequest>;

/**
 * @generated from service agntcy.dir.runtime.v1.RuntimeService
 */
export declare const RuntimeService: GenService<{
  /**
   * List all record processes based on filters.
   *
   * @generated from rpc agntcy.dir.runtime.v1.RuntimeService.ListProcesses
   */
  listProcesses: {
    methodKind: "server_streaming";
    input: typeof ListProcessesRequestSchema;
    output: typeof ProcessSchema;
  },
}>;

