# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: '3'

vars:
  BIN_DIR: '{{ .ROOT_DIR }}/bin'
  REGCLIENT_VERSION: '0.9.0'
  REGCLIENT_BIN: '{{ .BIN_DIR }}/regclient-{{.REGCLIENT_VERSION}}'

tasks:
  deps:bin-dir:
    desc: Create bin directory
    internal: true
    run: once
    cmd: mkdir -p {{.BIN_DIR}}
    status:
      - test -d {{.BIN_DIR}}

  deps:regclient:
    desc: Install regclient
    internal: true
    deps:
      - deps:bin-dir
    cmds:
      - curl -sfL https://github.com/regclient/regclient/releases/download/v{{.REGCLIENT_VERSION}}/regctl-{{OS}}-{{ARCH}} -o {{.REGCLIENT_BIN}}
      - chmod +x {{.REGCLIENT_BIN}}
    status:
      - test -x {{.REGCLIENT_BIN}}

  sign-poc:
    deps:
      - task: deps:regclient
    cmds:
      - docker compose up -d
      - go run main.go
      - docker compose down -v
      - rm -f cosign.key cosign.pub
