# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: example-record
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  record.json: |
    {{- .Values.record | nindent 4 }}
