# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: "3"

tasks:
  server:build:
    dir: ../
    desc: Build Directory server image
    cmds:
      - "{{.BAKE_ENV}} docker buildx bake {{.IMAGE_BAKE_OPTS}} dir-apiserver"

  server:start:
    desc: Start Directory server
    dir: ./cmd
    env:
      # Local development settings:
      # - Faster publication scheduling for quicker feedback
      DIRECTORY_SERVER_PUBLICATION_SCHEDULER_INTERVAL: 1s
      # - OASF validation uses OASF API (schema URL is required)
      DIRECTORY_SERVER_OASF_API_VALIDATION_SCHEMA_URL: "https://schema.oasf.outshift.com"
      # - Use SQLite for local development (no PostgreSQL required)
      DIRECTORY_SERVER_DATABASE_DB_TYPE: sqlite
      DIRECTORY_SERVER_DATABASE_SQLITE_DB_PATH: /tmp/dir.db
    cmds:
      - defer: { task: server:store:stop }
      - task: server:store:start
      - go run main.go

  server:store:pull:
    desc: Pull local OCI registry server docker image
    internal: true
    cmd: docker pull "{{.ZOT_IMAGE}}"
    status:
      - docker image inspect "{{.ZOT_IMAGE}}" > /dev/null 2>&1 || exit 1

  server:store:start:
    desc: Start local OCI registry server for storage
    internal: true
    deps:
      - task: server:store:pull
    cmds:
      - |
        # mount config
        cat > /tmp/config.json <<EOF
        {
          "distSpecVersion": "1.1.1",
          "storage": {
            "rootDirectory": "/tmp/zot"
          },
          "http": {
            "address": "0.0.0.0",
            "port": "5000"
          },
          "log": {
            "level": "debug"
          },
          "extensions": {
            "search": {
              "enable": true
            },
            "trust": {
              "enable": true,
              "cosign": true,
              "notation": false
            }
          }
        }
        EOF

        # run docker with attached volume
        docker run \
              -it \
              --rm -d -p 5000:5000 \
              -v /tmp/config.json:/config.json:ro \
              --name oci-registry {{.ZOT_IMAGE}} serve /config.json

  server:store:stop:
    desc: Stop local OCI registry node
    cmds:
      - docker stop oci-registry

  server:bench:
    desc: Benchmark Directory server code
    cmds:
      - go -C . test -run=^$ -bench=. ./...
