// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/search/v1/record_query.proto (package agntcy.dir.search.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file agntcy/dir/search/v1/record_query.proto.
 */
export const file_agntcy_dir_search_v1_record_query = /*@__PURE__*/
  fileDesc("CidhZ250Y3kvZGlyL3NlYXJjaC92MS9yZWNvcmRfcXVlcnkucHJvdG8SFGFnbnRjeS5kaXIuc2VhcmNoLnYxIlEKC1JlY29yZFF1ZXJ5EjMKBHR5cGUYASABKA4yJS5hZ250Y3kuZGlyLnNlYXJjaC52MS5SZWNvcmRRdWVyeVR5cGUSDQoFdmFsdWUYAiABKAkqvgMKD1JlY29yZFF1ZXJ5VHlwZRIhCh1SRUNPUkRfUVVFUllfVFlQRV9VTlNQRUNJRklFRBAAEhoKFlJFQ09SRF9RVUVSWV9UWVBFX05BTUUQARIdChlSRUNPUkRfUVVFUllfVFlQRV9WRVJTSU9OEAISHgoaUkVDT1JEX1FVRVJZX1RZUEVfU0tJTExfSUQQAxIgChxSRUNPUkRfUVVFUllfVFlQRV9TS0lMTF9OQU1FEAQSHQoZUkVDT1JEX1FVRVJZX1RZUEVfTE9DQVRPUhAFEiEKHVJFQ09SRF9RVUVSWV9UWVBFX01PRFVMRV9OQU1FEAYSHwobUkVDT1JEX1FVRVJZX1RZUEVfRE9NQUlOX0lEEAcSIQodUkVDT1JEX1FVRVJZX1RZUEVfRE9NQUlOX05BTUUQCBIgChxSRUNPUkRfUVVFUllfVFlQRV9DUkVBVEVEX0FUEAkSHAoYUkVDT1JEX1FVRVJZX1RZUEVfQVVUSE9SEAoSJAogUkVDT1JEX1FVRVJZX1RZUEVfU0NIRU1BX1ZFUlNJT04QCxIfChtSRUNPUkRfUVVFUllfVFlQRV9NT0RVTEVfSUQQDELEAQoYY29tLmFnbnRjeS5kaXIuc2VhcmNoLnYxQhBSZWNvcmRRdWVyeVByb3RvUAFaI2dpdGh1Yi5jb20vYWdudGN5L2Rpci9hcGkvc2VhcmNoL3YxogIDQURTqgIUQWdudGN5LkRpci5TZWFyY2guVjHKAhRBZ250Y3lcRGlyXFNlYXJjaFxWMeICIEFnbnRjeVxEaXJcU2VhcmNoXFYxXEdQQk1ldGFkYXRh6gIXQWdudGN5OjpEaXI6OlNlYXJjaDo6VjFiBnByb3RvMw");

/**
 * Describes the message agntcy.dir.search.v1.RecordQuery.
 * Use `create(RecordQuerySchema)` to create a new message.
 */
export const RecordQuerySchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_search_v1_record_query, 0);

/**
 * Describes the enum agntcy.dir.search.v1.RecordQueryType.
 */
export const RecordQueryTypeSchema = /*@__PURE__*/
  enumDesc(file_agntcy_dir_search_v1_record_query, 0);

/**
 * Defines a list of supported record query types.
 *
 * @generated from enum agntcy.dir.search.v1.RecordQueryType
 */
export const RecordQueryType = /*@__PURE__*/
  tsEnum(RecordQueryTypeSchema);

