// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/search/v1/search_service.proto (package agntcy.dir.search.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_agntcy_dir_core_v1_record } from "../../core/v1/record_pb.js";
import { file_agntcy_dir_search_v1_record_query } from "./record_query_pb.js";

/**
 * Describes the file agntcy/dir/search/v1/search_service.proto.
 */
export const file_agntcy_dir_search_v1_search_service = /*@__PURE__*/
  fileDesc("CilhZ250Y3kvZGlyL3NlYXJjaC92MS9zZWFyY2hfc2VydmljZS5wcm90bxIUYWdudGN5LmRpci5zZWFyY2gudjEihQEKEVNlYXJjaENJRHNSZXF1ZXN0EjIKB3F1ZXJpZXMYASADKAsyIS5hZ250Y3kuZGlyLnNlYXJjaC52MS5SZWNvcmRRdWVyeRISCgVsaW1pdBgCIAEoDUgAiAEBEhMKBm9mZnNldBgDIAEoDUgBiAEBQggKBl9saW1pdEIJCgdfb2Zmc2V0IogBChRTZWFyY2hSZWNvcmRzUmVxdWVzdBIyCgdxdWVyaWVzGAEgAygLMiEuYWdudGN5LmRpci5zZWFyY2gudjEuUmVjb3JkUXVlcnkSEgoFbGltaXQYAiABKA1IAIgBARITCgZvZmZzZXQYAyABKA1IAYgBAUIICgZfbGltaXRCCQoHX29mZnNldCIoChJTZWFyY2hDSURzUmVzcG9uc2USEgoKcmVjb3JkX2NpZBgBIAEoCSJDChVTZWFyY2hSZWNvcmRzUmVzcG9uc2USKgoGcmVjb3JkGAEgASgLMhouYWdudGN5LmRpci5jb3JlLnYxLlJlY29yZDLeAQoNU2VhcmNoU2VydmljZRJhCgpTZWFyY2hDSURzEicuYWdudGN5LmRpci5zZWFyY2gudjEuU2VhcmNoQ0lEc1JlcXVlc3QaKC5hZ250Y3kuZGlyLnNlYXJjaC52MS5TZWFyY2hDSURzUmVzcG9uc2UwARJqCg1TZWFyY2hSZWNvcmRzEiouYWdudGN5LmRpci5zZWFyY2gudjEuU2VhcmNoUmVjb3Jkc1JlcXVlc3QaKy5hZ250Y3kuZGlyLnNlYXJjaC52MS5TZWFyY2hSZWNvcmRzUmVzcG9uc2UwAULGAQoYY29tLmFnbnRjeS5kaXIuc2VhcmNoLnYxQhJTZWFyY2hTZXJ2aWNlUHJvdG9QAVojZ2l0aHViLmNvbS9hZ250Y3kvZGlyL2FwaS9zZWFyY2gvdjGiAgNBRFOqAhRBZ250Y3kuRGlyLlNlYXJjaC5WMcoCFEFnbnRjeVxEaXJcU2VhcmNoXFYx4gIgQWdudGN5XERpclxTZWFyY2hcVjFcR1BCTWV0YWRhdGHqAhdBZ250Y3k6OkRpcjo6U2VhcmNoOjpWMWIGcHJvdG8z", [file_agntcy_dir_core_v1_record, file_agntcy_dir_search_v1_record_query]);

/**
 * Describes the message agntcy.dir.search.v1.SearchCIDsRequest.
 * Use `create(SearchCIDsRequestSchema)` to create a new message.
 */
export const SearchCIDsRequestSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_search_v1_search_service, 0);

/**
 * Describes the message agntcy.dir.search.v1.SearchRecordsRequest.
 * Use `create(SearchRecordsRequestSchema)` to create a new message.
 */
export const SearchRecordsRequestSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_search_v1_search_service, 1);

/**
 * Describes the message agntcy.dir.search.v1.SearchCIDsResponse.
 * Use `create(SearchCIDsResponseSchema)` to create a new message.
 */
export const SearchCIDsResponseSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_search_v1_search_service, 2);

/**
 * Describes the message agntcy.dir.search.v1.SearchRecordsResponse.
 * Use `create(SearchRecordsResponseSchema)` to create a new message.
 */
export const SearchRecordsResponseSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_search_v1_search_service, 3);

/**
 * @generated from service agntcy.dir.search.v1.SearchService
 */
export const SearchService = /*@__PURE__*/
  serviceDesc(file_agntcy_dir_search_v1_search_service, 0);

