// SPDX-FileCopyrightText: Copyright (c) 2025 Cisco and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: routing/v1alpha1/routing_service.proto

package routingv1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	RoutingService_Provide_FullMethodName = "/routing.v1alpha1.RoutingService/Provide"
	RoutingService_Resolve_FullMethodName = "/routing.v1alpha1.RoutingService/Resolve"
	RoutingService_Lookup_FullMethodName  = "/routing.v1alpha1.RoutingService/Lookup"
	RoutingService_List_FullMethodName    = "/routing.v1alpha1.RoutingService/List"
)

// RoutingServiceClient is the client API for RoutingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Defines an interface for publication and retrieval
// of objects across interconnected network.
type RoutingServiceClient interface {
	// Notifies the network that the node is providing this path.
	// Path may be an actual item on the object store.
	Provide(ctx context.Context, in *Path, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Resolve all the nodes that are providing this path.
	Resolve(ctx context.Context, in *Path, opts ...grpc.CallOption) (RoutingService_ResolveClient, error)
	// Check if a given node has this path.
	Lookup(ctx context.Context, in *Path, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List a given path. Only first children are returned.
	List(ctx context.Context, in *Path, opts ...grpc.CallOption) (RoutingService_ListClient, error)
}

type routingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoutingServiceClient(cc grpc.ClientConnInterface) RoutingServiceClient {
	return &routingServiceClient{cc}
}

func (c *routingServiceClient) Provide(ctx context.Context, in *Path, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RoutingService_Provide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) Resolve(ctx context.Context, in *Path, opts ...grpc.CallOption) (RoutingService_ResolveClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RoutingService_ServiceDesc.Streams[0], RoutingService_Resolve_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &routingServiceResolveClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RoutingService_ResolveClient interface {
	Recv() (*Nodes, error)
	grpc.ClientStream
}

type routingServiceResolveClient struct {
	grpc.ClientStream
}

func (x *routingServiceResolveClient) Recv() (*Nodes, error) {
	m := new(Nodes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *routingServiceClient) Lookup(ctx context.Context, in *Path, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RoutingService_Lookup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) List(ctx context.Context, in *Path, opts ...grpc.CallOption) (RoutingService_ListClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RoutingService_ServiceDesc.Streams[1], RoutingService_List_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &routingServiceListClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RoutingService_ListClient interface {
	Recv() (*Paths, error)
	grpc.ClientStream
}

type routingServiceListClient struct {
	grpc.ClientStream
}

func (x *routingServiceListClient) Recv() (*Paths, error) {
	m := new(Paths)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RoutingServiceServer is the server API for RoutingService service.
// All implementations should embed UnimplementedRoutingServiceServer
// for forward compatibility.
//
// Defines an interface for publication and retrieval
// of objects across interconnected network.
type RoutingServiceServer interface {
	// Notifies the network that the node is providing this path.
	// Path may be an actual item on the object store.
	Provide(context.Context, *Path) (*emptypb.Empty, error)
	// Resolve all the nodes that are providing this path.
	Resolve(*Path, RoutingService_ResolveServer) error
	// Check if a given node has this path.
	Lookup(context.Context, *Path) (*emptypb.Empty, error)
	// List a given path. Only first children are returned.
	List(*Path, RoutingService_ListServer) error
}

// UnimplementedRoutingServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoutingServiceServer struct{}

func (UnimplementedRoutingServiceServer) Provide(context.Context, *Path) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Provide not implemented")
}
func (UnimplementedRoutingServiceServer) Resolve(*Path, RoutingService_ResolveServer) error {
	return status.Errorf(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedRoutingServiceServer) Lookup(context.Context, *Path) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lookup not implemented")
}
func (UnimplementedRoutingServiceServer) List(*Path, RoutingService_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedRoutingServiceServer) testEmbeddedByValue() {}

// UnsafeRoutingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoutingServiceServer will
// result in compilation errors.
type UnsafeRoutingServiceServer interface {
	mustEmbedUnimplementedRoutingServiceServer()
}

func RegisterRoutingServiceServer(s grpc.ServiceRegistrar, srv RoutingServiceServer) {
	// If the following call pancis, it indicates UnimplementedRoutingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoutingService_ServiceDesc, srv)
}

func _RoutingService_Provide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Path)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).Provide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_Provide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).Provide(ctx, req.(*Path))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_Resolve_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Path)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RoutingServiceServer).Resolve(m, &routingServiceResolveServer{ServerStream: stream})
}

type RoutingService_ResolveServer interface {
	Send(*Nodes) error
	grpc.ServerStream
}

type routingServiceResolveServer struct {
	grpc.ServerStream
}

func (x *routingServiceResolveServer) Send(m *Nodes) error {
	return x.ServerStream.SendMsg(m)
}

func _RoutingService_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Path)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_Lookup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).Lookup(ctx, req.(*Path))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Path)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RoutingServiceServer).List(m, &routingServiceListServer{ServerStream: stream})
}

type RoutingService_ListServer interface {
	Send(*Paths) error
	grpc.ServerStream
}

type routingServiceListServer struct {
	grpc.ServerStream
}

func (x *routingServiceListServer) Send(m *Paths) error {
	return x.ServerStream.SendMsg(m)
}

// RoutingService_ServiceDesc is the grpc.ServiceDesc for RoutingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoutingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "routing.v1alpha1.RoutingService",
	HandlerType: (*RoutingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Provide",
			Handler:    _RoutingService_Provide_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _RoutingService_Lookup_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Resolve",
			Handler:       _RoutingService_Resolve_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "List",
			Handler:       _RoutingService_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "routing/v1alpha1/routing_service.proto",
}
