# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: Setup dirctl
description: |
  Install the dirctl CLI and add it to PATH.
  Downloads the binary from GitHub releases.
author: agntcy
branding:
  icon: settings
  color: yellow

inputs:
  version:
    description: Release tag (e.g. v1.0.0) or "latest"
    required: false
    default: "latest"
  os:
    description: Operating system (linux, darwin, windows)
    required: false
    default: "linux"
  arch:
    description: Architecture (amd64, arm64)
    required: false
    default: "amd64"

runs:
  using: "composite"
  steps:
    - name: Setup dirctl
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        OS: ${{ inputs.os }}
        ARCH: ${{ inputs.arch }}
      run: |
        chmod +x "${{ github.action_path }}/setup-dirctl.sh"
        "${{ github.action_path }}/setup-dirctl.sh"
