# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

regcred:
  create: false

apiserver:
  image:
    repository: ghcr.io/agntcy/dir-apiserver
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: NodePort

  config:
    server_port: 8888
    health_port: 8889
    provider: "oci"
    oci_registry_address: "dir-zot:5000"
    oci_auth_config_insecure: "true"
