# SPDX-FileCopyrightText: Copyright (c) 2025 Cisco and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

regcred:
  create: false

apiserver:
  image:
    repository: ghcr.io/agntcy/dir-apiserver
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: NodePort

  config:
    provider: "oci"
    oci_registry_address: "dir-zot:5000"
