# SPDX-FileCopyrightText: Copyright (c) 2025 Cisco and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

apiserver:
  image:
    repository: ghcr.io/agntcy/dir-apiserver
    tag: latest
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: regcred

  config:
    server_port: 8888
    health_port: 8889
    provider: "oci"
    oci_registry_address: "agntcy-dir-zot.default.svc.cluster.local:5000"

  service:
    type: NodePort
