# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: Push OASF Record
description: |
  Push agent records to a Directory node's OCI registry.
author: agntcy
branding:
  icon: upload-cloud
  color: blue

inputs:
  record_paths:
    description: |
      Paths to OASF record JSON files to push (one per line).
      Supports glob patterns (e.g., "agents/*.json").
    required: false
    default: "record.json"
  server_addr:
    description: Optional Directory server address (host:port). Uses dirctl default if omitted.
    required: false
    default: ""
  github_token:
    description: Optional GitHub PAT for Directory authentication
    required: false
    default: ""

outputs:
  success:
    description: Whether all records were pushed successfully ("true" or "false")
    value: ${{ steps.push.outputs.success }}
  cids:
    description: JSON object mapping file paths to their CIDs
    value: ${{ steps.push.outputs.cids }}
  failed_files:
    description: JSON array of file paths that failed to push
    value: ${{ steps.push.outputs.failed_files }}

runs:
  using: "composite"
  steps:
    - name: Push records
      id: push
      shell: bash
      env:
        RECORD_PATHS: ${{ inputs.record_paths }}
        SERVER_ADDR: ${{ inputs.server_addr }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        chmod +x "${{ github.action_path }}/push.sh"
        "${{ github.action_path }}/push.sh"
