// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "objects/v2/agent_record.proto" (package "objects.v2", syntax proto3)
// tslint:disable
//
// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Signature } from "./signature";
import { Extension } from "./extension";
import { Locator } from "./locator";
import { Skill } from "./skill";
/**
 * AgentRecord defines a schema for versioned AI agent content representation.
 * The schema provides a way to describe an agent in a structured format.
 *
 * This is a versioned gRPC-based OASF schema.
 *
 * Max size: 4 MB (or to fully fit in a single request)
 * It may be required to support larger agent record size in the future.
 *
 * AgentRecords are stored in a content-addressable store.
 * AgentRecords can be indexed for quick lookups and searches to avoid unnecessary data transfer.
 *
 * All agent records are referenced by a globally-unique content identifier (CID).
 * Specs: https://github.com/multiformats/cid
 *
 * @generated from protobuf message objects.v2.AgentRecord
 */
export interface AgentRecord {
    /**
     * Name of the agent.
     *
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * Version of the agent.
     *
     * @generated from protobuf field: string version = 2
     */
    version: string;
    /**
     * Schema version of the agent.
     *
     * @generated from protobuf field: string schema_version = 3
     */
    schemaVersion: string;
    /**
     * Description of the agent.
     *
     * @generated from protobuf field: string description = 4
     */
    description: string;
    /**
     * List of agent authors, e.g. in the form of `author-name <author-email>`.
     *
     * @generated from protobuf field: repeated string authors = 5
     */
    authors: string[];
    /**
     * Metadata associated with the agent.
     *
     * @generated from protobuf field: map<string, string> annotations = 6
     */
    annotations: {
        [key: string]: string;
    };
    /**
     * Creation timestamp of the agent in the RFC3339 format.
     * Specs: https://www.rfc-editor.org/rfc/rfc3339.html
     *
     * @generated from protobuf field: string created_at = 7
     */
    createdAt: string;
    /**
     * List of skills that the agent can perform.
     *
     * @generated from protobuf field: repeated objects.v2.Skill skills = 8
     */
    skills: Skill[];
    /**
     * List of source locators where the agent can be found or used from.
     *
     * @generated from protobuf field: repeated objects.v2.Locator locators = 9
     */
    locators: Locator[];
    /**
     * Additional information attached to the agent.
     * Extensions are used to generically extend the agent's functionality.
     *
     * @generated from protobuf field: repeated objects.v2.Extension extensions = 10
     */
    extensions: Extension[];
    /**
     * Security signature of the agent.
     *
     * @generated from protobuf field: objects.v2.Signature signature = 11
     */
    signature?: Signature;
    /**
     * Reference to the previous agent record, if any.
     * Used to link the agent record to its previous versions.
     * Field number is explicitly reserved for extendability.
     *
     * @generated from protobuf field: optional string previous_agent_record_cid = 99
     */
    previousAgentRecordCid?: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class AgentRecord$Type extends MessageType<AgentRecord> {
    constructor() {
        super("objects.v2.AgentRecord", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "schema_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "authors", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "annotations", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } },
            { no: 7, name: "created_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "skills", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Skill },
            { no: 9, name: "locators", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Locator },
            { no: 10, name: "extensions", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Extension },
            { no: 11, name: "signature", kind: "message", T: () => Signature },
            { no: 99, name: "previous_agent_record_cid", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AgentRecord>): AgentRecord {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.version = "";
        message.schemaVersion = "";
        message.description = "";
        message.authors = [];
        message.annotations = {};
        message.createdAt = "";
        message.skills = [];
        message.locators = [];
        message.extensions = [];
        if (value !== undefined)
            reflectionMergePartial<AgentRecord>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AgentRecord): AgentRecord {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string version */ 2:
                    message.version = reader.string();
                    break;
                case /* string schema_version */ 3:
                    message.schemaVersion = reader.string();
                    break;
                case /* string description */ 4:
                    message.description = reader.string();
                    break;
                case /* repeated string authors */ 5:
                    message.authors.push(reader.string());
                    break;
                case /* map<string, string> annotations */ 6:
                    this.binaryReadMap6(message.annotations, reader, options);
                    break;
                case /* string created_at */ 7:
                    message.createdAt = reader.string();
                    break;
                case /* repeated objects.v2.Skill skills */ 8:
                    message.skills.push(Skill.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated objects.v2.Locator locators */ 9:
                    message.locators.push(Locator.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated objects.v2.Extension extensions */ 10:
                    message.extensions.push(Extension.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* objects.v2.Signature signature */ 11:
                    message.signature = Signature.internalBinaryRead(reader, reader.uint32(), options, message.signature);
                    break;
                case /* optional string previous_agent_record_cid */ 99:
                    message.previousAgentRecordCid = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap6(map: AgentRecord["annotations"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof AgentRecord["annotations"] | undefined, val: AgentRecord["annotations"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for objects.v2.AgentRecord.annotations");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: AgentRecord, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string version = 2; */
        if (message.version !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.version);
        /* string schema_version = 3; */
        if (message.schemaVersion !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.schemaVersion);
        /* string description = 4; */
        if (message.description !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.description);
        /* repeated string authors = 5; */
        for (let i = 0; i < message.authors.length; i++)
            writer.tag(5, WireType.LengthDelimited).string(message.authors[i]);
        /* map<string, string> annotations = 6; */
        for (let k of globalThis.Object.keys(message.annotations))
            writer.tag(6, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.annotations[k]).join();
        /* string created_at = 7; */
        if (message.createdAt !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.createdAt);
        /* repeated objects.v2.Skill skills = 8; */
        for (let i = 0; i < message.skills.length; i++)
            Skill.internalBinaryWrite(message.skills[i], writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* repeated objects.v2.Locator locators = 9; */
        for (let i = 0; i < message.locators.length; i++)
            Locator.internalBinaryWrite(message.locators[i], writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* repeated objects.v2.Extension extensions = 10; */
        for (let i = 0; i < message.extensions.length; i++)
            Extension.internalBinaryWrite(message.extensions[i], writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        /* objects.v2.Signature signature = 11; */
        if (message.signature)
            Signature.internalBinaryWrite(message.signature, writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        /* optional string previous_agent_record_cid = 99; */
        if (message.previousAgentRecordCid !== undefined)
            writer.tag(99, WireType.LengthDelimited).string(message.previousAgentRecordCid);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message objects.v2.AgentRecord
 */
export const AgentRecord = new AgentRecord$Type();
