# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: "3"

tasks:
  default:
    cmd: echo "Run the main Taskfile instead of this one."

  api:gen:
    desc: Generates API stubs
    dir: ./proto
    deps:
      - task: deps:protoc
      - task: deps:bufbuild
    # NOTE(ramizpolic): This allows Taskfile YAML parsing to accept '{' as a starting command token.
    # In translation, this is interpreted as a regular multi-line shell script.
    cmds:
      - "{{.BUFBUILD_BIN}} dep update"
      - "{{.BUFBUILD_BIN}} generate --template buf.gen.yaml"

  api:clean:
    desc: Clean generated API stubs
    dir: ./api
    cmds:
      - find . \( -name "*.pb.go" \) -type f -delete

  api:clean:runtime:go:
    desc: Clean runtime generated golang API stubs
    dir: ./runtime
    cmds:
      - find . \( -name "*.pb.go" \) -type f -delete
