# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from agntcy.dir.naming.v1 import naming_service_pb2 as agntcy_dot_dir_dot_naming_dot_v1_dot_naming__service__pb2


class NamingServiceStub(object):
    """NamingService provides methods to verify and check domain ownership.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifyDomain = channel.unary_unary(
                '/agntcy.dir.naming.v1.NamingService/VerifyDomain',
                request_serializer=agntcy_dot_dir_dot_naming_dot_v1_dot_naming__service__pb2.VerifyDomainRequest.SerializeToString,
                response_deserializer=agntcy_dot_dir_dot_naming_dot_v1_dot_naming__service__pb2.VerifyDomainResponse.FromString,
                _registered_method=True)
        self.CheckDomainVerification = channel.unary_unary(
                '/agntcy.dir.naming.v1.NamingService/CheckDomainVerification',
                request_serializer=agntcy_dot_dir_dot_naming_dot_v1_dot_naming__service__pb2.CheckDomainVerificationRequest.SerializeToString,
                response_deserializer=agntcy_dot_dir_dot_naming_dot_v1_dot_naming__service__pb2.CheckDomainVerificationResponse.FromString,
                _registered_method=True)


class NamingServiceServicer(object):
    """NamingService provides methods to verify and check domain ownership.
    """

    def VerifyDomain(self, request, context):
        """VerifyDomain performs domain ownership verification for a signed record.
        This should be called after signing a record to verify and store the domain ownership proof.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckDomainVerification(self, request, context):
        """CheckDomainVerification checks if a record has verified domain ownership.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NamingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifyDomain': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyDomain,
                    request_deserializer=agntcy_dot_dir_dot_naming_dot_v1_dot_naming__service__pb2.VerifyDomainRequest.FromString,
                    response_serializer=agntcy_dot_dir_dot_naming_dot_v1_dot_naming__service__pb2.VerifyDomainResponse.SerializeToString,
            ),
            'CheckDomainVerification': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckDomainVerification,
                    request_deserializer=agntcy_dot_dir_dot_naming_dot_v1_dot_naming__service__pb2.CheckDomainVerificationRequest.FromString,
                    response_serializer=agntcy_dot_dir_dot_naming_dot_v1_dot_naming__service__pb2.CheckDomainVerificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agntcy.dir.naming.v1.NamingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agntcy.dir.naming.v1.NamingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NamingService(object):
    """NamingService provides methods to verify and check domain ownership.
    """

    @staticmethod
    def VerifyDomain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agntcy.dir.naming.v1.NamingService/VerifyDomain',
            agntcy_dot_dir_dot_naming_dot_v1_dot_naming__service__pb2.VerifyDomainRequest.SerializeToString,
            agntcy_dot_dir_dot_naming_dot_v1_dot_naming__service__pb2.VerifyDomainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckDomainVerification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agntcy.dir.naming.v1.NamingService/CheckDomainVerification',
            agntcy_dot_dir_dot_naming_dot_v1_dot_naming__service__pb2.CheckDomainVerificationRequest.SerializeToString,
            agntcy_dot_dir_dot_naming_dot_v1_dot_naming__service__pb2.CheckDomainVerificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
