// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: agntcy/dir/policy/v1/policy_audit_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	PolicyAuditService_GetRecord_FullMethodName           = "/agntcy.dir.policy.v1.PolicyAuditService/GetRecord"
	PolicyAuditService_ListExcludedRecords_FullMethodName = "/agntcy.dir.policy.v1.PolicyAuditService/ListExcludedRecords"
)

// PolicyAuditServiceClient is the client API for PolicyAuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PolicyAuditService lets an auditor see records the enforced content
// policies exclude from every other read. It is a separate service so that it
// is authorized on its own: only a policy naming the caller's SPIFFE ID
// grants it, never one for a whole trust domain, and the server offers it
// only when authorization is enabled. Every call is audit-logged.
type PolicyAuditServiceClient interface {
	// GetRecord returns a record by CID whether or not the enforced policies
	// exclude it, with its policy verdicts.
	GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*GetRecordResponse, error)
	// ListExcludedRecords lists the indexed records the enforced policies
	// exclude, with their verdicts.
	ListExcludedRecords(ctx context.Context, in *ListExcludedRecordsRequest, opts ...grpc.CallOption) (PolicyAuditService_ListExcludedRecordsClient, error)
}

type policyAuditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyAuditServiceClient(cc grpc.ClientConnInterface) PolicyAuditServiceClient {
	return &policyAuditServiceClient{cc}
}

func (c *policyAuditServiceClient) GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*GetRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecordResponse)
	err := c.cc.Invoke(ctx, PolicyAuditService_GetRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyAuditServiceClient) ListExcludedRecords(ctx context.Context, in *ListExcludedRecordsRequest, opts ...grpc.CallOption) (PolicyAuditService_ListExcludedRecordsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PolicyAuditService_ServiceDesc.Streams[0], PolicyAuditService_ListExcludedRecords_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &policyAuditServiceListExcludedRecordsClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PolicyAuditService_ListExcludedRecordsClient interface {
	Recv() (*ListExcludedRecordsResponse, error)
	grpc.ClientStream
}

type policyAuditServiceListExcludedRecordsClient struct {
	grpc.ClientStream
}

func (x *policyAuditServiceListExcludedRecordsClient) Recv() (*ListExcludedRecordsResponse, error) {
	m := new(ListExcludedRecordsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PolicyAuditServiceServer is the server API for PolicyAuditService service.
// All implementations should embed UnimplementedPolicyAuditServiceServer
// for forward compatibility.
//
// PolicyAuditService lets an auditor see records the enforced content
// policies exclude from every other read. It is a separate service so that it
// is authorized on its own: only a policy naming the caller's SPIFFE ID
// grants it, never one for a whole trust domain, and the server offers it
// only when authorization is enabled. Every call is audit-logged.
type PolicyAuditServiceServer interface {
	// GetRecord returns a record by CID whether or not the enforced policies
	// exclude it, with its policy verdicts.
	GetRecord(context.Context, *GetRecordRequest) (*GetRecordResponse, error)
	// ListExcludedRecords lists the indexed records the enforced policies
	// exclude, with their verdicts.
	ListExcludedRecords(*ListExcludedRecordsRequest, PolicyAuditService_ListExcludedRecordsServer) error
}

// UnimplementedPolicyAuditServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyAuditServiceServer struct{}

func (UnimplementedPolicyAuditServiceServer) GetRecord(context.Context, *GetRecordRequest) (*GetRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecord not implemented")
}
func (UnimplementedPolicyAuditServiceServer) ListExcludedRecords(*ListExcludedRecordsRequest, PolicyAuditService_ListExcludedRecordsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListExcludedRecords not implemented")
}
func (UnimplementedPolicyAuditServiceServer) testEmbeddedByValue() {}

// UnsafePolicyAuditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyAuditServiceServer will
// result in compilation errors.
type UnsafePolicyAuditServiceServer interface {
	mustEmbedUnimplementedPolicyAuditServiceServer()
}

func RegisterPolicyAuditServiceServer(s grpc.ServiceRegistrar, srv PolicyAuditServiceServer) {
	// If the following call pancis, it indicates UnimplementedPolicyAuditServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicyAuditService_ServiceDesc, srv)
}

func _PolicyAuditService_GetRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyAuditServiceServer).GetRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyAuditService_GetRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyAuditServiceServer).GetRecord(ctx, req.(*GetRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyAuditService_ListExcludedRecords_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListExcludedRecordsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PolicyAuditServiceServer).ListExcludedRecords(m, &policyAuditServiceListExcludedRecordsServer{ServerStream: stream})
}

type PolicyAuditService_ListExcludedRecordsServer interface {
	Send(*ListExcludedRecordsResponse) error
	grpc.ServerStream
}

type policyAuditServiceListExcludedRecordsServer struct {
	grpc.ServerStream
}

func (x *policyAuditServiceListExcludedRecordsServer) Send(m *ListExcludedRecordsResponse) error {
	return x.ServerStream.SendMsg(m)
}

// PolicyAuditService_ServiceDesc is the grpc.ServiceDesc for PolicyAuditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyAuditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agntcy.dir.policy.v1.PolicyAuditService",
	HandlerType: (*PolicyAuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecord",
			Handler:    _PolicyAuditService_GetRecord_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListExcludedRecords",
			Handler:       _PolicyAuditService_ListExcludedRecords_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agntcy/dir/policy/v1/policy_audit_service.proto",
}
