# Discovery Service - Kubernetes Deployment
# Includes: etcd, watcher (with RBAC), server, test workloads, and network policy
#
# Usage:
#   kubectl apply -f k8s.discovery.yaml
#   kubectl wait --for=condition=ready pod -l app=etcd --timeout=60s
#   kubectl wait --for=condition=ready pod -l app=discovery-watcher --timeout=60s
#   kubectl wait --for=condition=ready pod -l app=discovery-server --timeout=60s
#   kubectl wait --for=condition=ready pod -l discover=true -n team-a --timeout=60s
#   kubectl wait --for=condition=ready pod -l discover=true -n team-b --timeout=60s
#
# Test:
#   kubectl port-forward svc/discovery-server 8080:8080 &
#   curl http://localhost:8080/workloads | jq .
#
# ============================================================================
# ETCD
# ============================================================================
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-etcd
  namespace: default
spec:
  ports:
    - port: 2379
      targetPort: 2379
  selector:
    app: discovery-etcd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-etcd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-etcd
  template:
    metadata:
      labels:
        app: discovery-etcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.9
          command:
            - etcd
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://discovery-etcd:2379
          ports:
            - containerPort: 2379
# ============================================================================
# WATCHER (with RBAC)
# ============================================================================
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: discovery-watcher
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: discovery-watcher
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: discovery-watcher
subjects:
  - kind: ServiceAccount
    name: discovery-watcher
    namespace: default
roleRef:
  kind: ClusterRole
  name: discovery-watcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-watcher
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-watcher
  template:
    metadata:
      labels:
        app: discovery-watcher
    spec:
      serviceAccountName: discovery-watcher
      containers:
        - name: watcher
          image: discovery-watcher:latest
          imagePullPolicy: Never
          env:
            - name: RUNTIME
              value: "kubernetes"
            - name: KUBERNETES_IN_CLUSTER
              value: "true"
            - name: KUBERNETES_LABEL_KEY
              value: "discover"
            - name: KUBERNETES_LABEL_VALUE
              value: "true"
            - name: ETCD_HOST
              value: "discovery-etcd"
            - name: ETCD_PORT
              value: "2379"
# ============================================================================
# SERVER
# ============================================================================
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: discovery-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: server
          image: discovery-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: ETCD_HOST
              value: "discovery-etcd"
            - name: ETCD_PORT
              value: "2379"
# ============================================================================
# TEST WORKLOADS (namespaces act as isolation groups)
# Pods use hostname + subdomain + headless service for DNS resolution
# Format: {hostname}.{subdomain}.{namespace}.svc.cluster.local
# ============================================================================
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-a
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-b
---
# Headless service for team-a pods (enables DNS for pods)
apiVersion: v1
kind: Service
metadata:
  name: team-a
  namespace: team-a
spec:
  clusterIP: None
  selector:
    discover: "true"
  ports:
    - port: 80
      targetPort: 80
---
# Headless service for team-b pods (enables DNS for pods)
apiVersion: v1
kind: Service
metadata:
  name: team-b
  namespace: team-b
spec:
  clusterIP: None
  selector:
    discover: "true"
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: service-1
  namespace: team-a
  labels:
    discover: "true"
    app: service-1
spec:
  hostname: service-1
  subdomain: team-a
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: service-3
  namespace: team-a
  labels:
    discover: "true"
    app: service-3
spec:
  hostname: service-3
  subdomain: team-a
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: service-2
  namespace: team-b
  labels:
    discover: "true"
    app: service-2
spec:
  hostname: service-2
  subdomain: team-b
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: service-4
  namespace: team-b
  labels:
    discover: "true"
    app: service-4
spec:
  hostname: service-4
  subdomain: team-b
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
# ============================================================================
# NETWORK POLICY (optional - tests NetworkPolicy detection)
# ============================================================================
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: team-a
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
