# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from sign.v1alpha1 import sign_service_pb2 as sign_dot_v1alpha1_dot_sign__service__pb2


class SignServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SignOIDC = channel.unary_unary(
                '/sign.v1alpha1.SignService/SignOIDC',
                request_serializer=sign_dot_v1alpha1_dot_sign__service__pb2.SignOIDCRequest.SerializeToString,
                response_deserializer=sign_dot_v1alpha1_dot_sign__service__pb2.SignOIDCResponse.FromString,
                _registered_method=True)
        self.SignWithKey = channel.unary_unary(
                '/sign.v1alpha1.SignService/SignWithKey',
                request_serializer=sign_dot_v1alpha1_dot_sign__service__pb2.SignWithKeyRequest.SerializeToString,
                response_deserializer=sign_dot_v1alpha1_dot_sign__service__pb2.SignWithKeyResponse.FromString,
                _registered_method=True)
        self.VerifyOIDC = channel.unary_unary(
                '/sign.v1alpha1.SignService/VerifyOIDC',
                request_serializer=sign_dot_v1alpha1_dot_sign__service__pb2.VerifyOIDCRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.VerifyWithKey = channel.unary_unary(
                '/sign.v1alpha1.SignService/VerifyWithKey',
                request_serializer=sign_dot_v1alpha1_dot_sign__service__pb2.VerifyWithKeyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class SignServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SignOIDC(self, request, context):
        """Sign agents using one of the auth methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignWithKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyOIDC(self, request, context):
        """Verify signed agents using on of the auth methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyWithKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SignServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SignOIDC': grpc.unary_unary_rpc_method_handler(
                    servicer.SignOIDC,
                    request_deserializer=sign_dot_v1alpha1_dot_sign__service__pb2.SignOIDCRequest.FromString,
                    response_serializer=sign_dot_v1alpha1_dot_sign__service__pb2.SignOIDCResponse.SerializeToString,
            ),
            'SignWithKey': grpc.unary_unary_rpc_method_handler(
                    servicer.SignWithKey,
                    request_deserializer=sign_dot_v1alpha1_dot_sign__service__pb2.SignWithKeyRequest.FromString,
                    response_serializer=sign_dot_v1alpha1_dot_sign__service__pb2.SignWithKeyResponse.SerializeToString,
            ),
            'VerifyOIDC': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyOIDC,
                    request_deserializer=sign_dot_v1alpha1_dot_sign__service__pb2.VerifyOIDCRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'VerifyWithKey': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyWithKey,
                    request_deserializer=sign_dot_v1alpha1_dot_sign__service__pb2.VerifyWithKeyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sign.v1alpha1.SignService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sign.v1alpha1.SignService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SignService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SignOIDC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sign.v1alpha1.SignService/SignOIDC',
            sign_dot_v1alpha1_dot_sign__service__pb2.SignOIDCRequest.SerializeToString,
            sign_dot_v1alpha1_dot_sign__service__pb2.SignOIDCResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignWithKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sign.v1alpha1.SignService/SignWithKey',
            sign_dot_v1alpha1_dot_sign__service__pb2.SignWithKeyRequest.SerializeToString,
            sign_dot_v1alpha1_dot_sign__service__pb2.SignWithKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyOIDC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sign.v1alpha1.SignService/VerifyOIDC',
            sign_dot_v1alpha1_dot_sign__service__pb2.VerifyOIDCRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyWithKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sign.v1alpha1.SignService/VerifyWithKey',
            sign_dot_v1alpha1_dot_sign__service__pb2.VerifyWithKeyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
