{{- if .Values.rbac.create }}
# Required cluster role to allow spire-agent to query k8s API server
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spire.agent.fullname" . }}-cluster-role
  labels:
    {{- include "spire.agent.labels" . | nindent 4 }}
  {{- with (include "spire.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
rules:
- apiGroups: [""]
  resources: ["pods","nodes","nodes/proxy"]
  verbs: ["get"]
---
# Binds above cluster role to spire-agent service account
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spire.agent.fullname" . }}-cluster-role-binding
  labels:
    {{- include "spire.agent.labels" . | nindent 4 }}
  {{- with (include "spire.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "spire.agent.serviceAccountName" . }}
  namespace: {{ include "spire.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "spire.agent.fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}