apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "spire.server.fullname" . }}
  namespace: {{ include "spire.namespace" . }}
  labels:
    {{- include "spire.server.labels" . | nindent 4 }}
  {{- with (include "spire.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "spire.server.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "spire.server.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "spire.server.selectorLabels" . | nindent 8 }}
      {{- with (include "spire.annotations" .) }}
      annotations:
        {{- . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "spire.server.serviceAccountName" . }}
      {{- with .Values.server.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: spire-server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          args:
            - -config
            - /run/spire/config/server.conf
          ports:
            - containerPort: {{ .Values.server.config.bindPort }}
              name: grpc
              protocol: TCP
            {{- if .Values.server.healthChecks.enabled }}
            - containerPort: {{ .Values.server.healthChecks.bindPort }}
              name: healthz
              protocol: TCP
            {{- end }}
          volumeMounts:
            - name: spire-config
              mountPath: /run/spire/config
              readOnly: true
            - name: spire-data
              mountPath: /run/spire/data
              readOnly: false
          {{- if .Values.server.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.server.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.server.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.server.readinessProbe | nindent 12 }}
          {{- end }}
          {{- with .Values.server.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: spire-config
          configMap:
            name: {{ include "spire.server.fullname" . }}
  {{- if .Values.server.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: spire-data
        labels:
          {{- include "spire.server.labels" . | nindent 10 }}
      spec:
        {{- with .Values.server.persistence.accessModes }}
        accessModes:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.server.persistence.storageClass }}
        storageClassName: {{ .Values.server.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.server.persistence.size }}
  {{- else }}
        - name: spire-data
          emptyDir: {}
  {{- end }}
