{{- if .Values.rbac.create }}
# Role (namespace scoped) to be able to push certificate bundles to a configmap
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spire.server.fullname" . }}-configmap-role
  namespace: {{ include "spire.namespace" . }}
  labels:
    {{- include "spire.server.labels" . | nindent 4 }}
  {{- with (include "spire.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["patch", "get", "list"]
---
# Binds above role to spire-server service account
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spire.server.fullname" . }}-configmap-role-binding
  namespace: {{ include "spire.namespace" . }}
  labels:
    {{- include "spire.server.labels" . | nindent 4 }}
  {{- with (include "spire.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "spire.server.serviceAccountName" . }}
  namespace: {{ include "spire.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "spire.server.fullname" . }}-configmap-role
---
# ClusterRole to allow spire-server node attestor to read pods and nodes, and query Token Review API
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spire.server.fullname" . }}-trust-role
  labels:
    {{- include "spire.server.labels" . | nindent 4 }}
  {{- with (include "spire.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
---
# Binds above cluster role to spire-server service account
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spire.server.fullname" . }}-trust-role-binding
  labels:
    {{- include "spire.server.labels" . | nindent 4 }}
  {{- with (include "spire.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "spire.server.serviceAccountName" . }}
  namespace: {{ include "spire.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "spire.server.fullname" . }}-trust-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
