apiVersion: v1
kind: Service
metadata:
  name: {{ include "spire.server.fullname" . }}
  namespace: {{ include "spire.namespace" . }}
  labels:
    {{- include "spire.server.labels" . | nindent 4 }}
  {{- with (include "spire.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "spire.server.selectorLabels" . | nindent 4 }}
