{{- if .Values.bundle.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.bundle.configMap.name | default (printf "%s-bundle" (include "spire.fullname" .)) }}
  namespace: {{ include "spire.namespace" . }}
  labels:
    {{- include "spire.labels" . | nindent 4 }}
  {{- with (include "spire.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}