// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: agntcy/dir/catalog/v1/agent_finder_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AgentFinderService_ListAgents_FullMethodName = "/agntcy.dir.catalog.v1.AgentFinderService/ListAgents"
)

// AgentFinderServiceClient is the client API for AgentFinderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentFinderService implements the federated discovery surface defined by
// the Agent Finder Specification (v0.4.2).
//
// The service is exposed natively over gRPC and additionally as a REST API
// via grpc-gateway, as mandated by §3.5 of the spec ("Universal Baseline for
// Federation"): every Agent Registry MUST expose a standard HTTP REST search
// interface so that any HTTP client can participate in discovery.
type AgentFinderServiceClient interface {
	// ListAgents returns catalog entries with deterministic browsing semantics.
	//
	// Corresponds to §7.2 of the Agent Finder Specification: highly cacheable,
	// relies on strict database filtering, and does NOT support relevance-based
	// sorting. For semantic, ranked discovery, see the future Search RPC (§7.1).
	//
	// HTTP mapping:
	//
	//	GET /v1/agents?filter=...&orderBy=...&pageSize=...&pageToken=...
	//
	// Query parameters are bound from top-level scalar fields on the request
	// message per the grpc-gateway query-parameter rules.
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
}

type agentFinderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentFinderServiceClient(cc grpc.ClientConnInterface) AgentFinderServiceClient {
	return &agentFinderServiceClient{cc}
}

func (c *agentFinderServiceClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, AgentFinderService_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentFinderServiceServer is the server API for AgentFinderService service.
// All implementations should embed UnimplementedAgentFinderServiceServer
// for forward compatibility.
//
// AgentFinderService implements the federated discovery surface defined by
// the Agent Finder Specification (v0.4.2).
//
// The service is exposed natively over gRPC and additionally as a REST API
// via grpc-gateway, as mandated by §3.5 of the spec ("Universal Baseline for
// Federation"): every Agent Registry MUST expose a standard HTTP REST search
// interface so that any HTTP client can participate in discovery.
type AgentFinderServiceServer interface {
	// ListAgents returns catalog entries with deterministic browsing semantics.
	//
	// Corresponds to §7.2 of the Agent Finder Specification: highly cacheable,
	// relies on strict database filtering, and does NOT support relevance-based
	// sorting. For semantic, ranked discovery, see the future Search RPC (§7.1).
	//
	// HTTP mapping:
	//
	//	GET /v1/agents?filter=...&orderBy=...&pageSize=...&pageToken=...
	//
	// Query parameters are bound from top-level scalar fields on the request
	// message per the grpc-gateway query-parameter rules.
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
}

// UnimplementedAgentFinderServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentFinderServiceServer struct{}

func (UnimplementedAgentFinderServiceServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedAgentFinderServiceServer) testEmbeddedByValue() {}

// UnsafeAgentFinderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentFinderServiceServer will
// result in compilation errors.
type UnsafeAgentFinderServiceServer interface {
	mustEmbedUnimplementedAgentFinderServiceServer()
}

func RegisterAgentFinderServiceServer(s grpc.ServiceRegistrar, srv AgentFinderServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentFinderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentFinderService_ServiceDesc, srv)
}

func _AgentFinderService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentFinderServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentFinderService_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentFinderServiceServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentFinderService_ServiceDesc is the grpc.ServiceDesc for AgentFinderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentFinderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agntcy.dir.catalog.v1.AgentFinderService",
	HandlerType: (*AgentFinderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAgents",
			Handler:    _AgentFinderService_ListAgents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agntcy/dir/catalog/v1/agent_finder_service.proto",
}
