// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: agntcy/dir/catalog/v1/ai_finder_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AIFinderService_ListAgents_FullMethodName          = "/agntcy.dir.catalog.v1.AIFinderService/ListAgents"
	AIFinderService_GetWellKnownCatalog_FullMethodName = "/agntcy.dir.catalog.v1.AIFinderService/GetWellKnownCatalog"
)

// AIFinderServiceClient is the client API for AIFinderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AIFinderService is the federated AI Finder discovery surface over the AI
// Catalog model. It is exposed over gRPC and, via grpc-gateway, as a REST API.
type AIFinderServiceClient interface {
	// ListAgents returns catalog entries with deterministic, cacheable browsing
	// semantics (database filtering, no relevance ranking).
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	// GetWellKnownCatalog returns the AI Catalog well-known document (host
	// descriptor, published entries, and dynamic collections) at the RFC 8615 URI.
	GetWellKnownCatalog(ctx context.Context, in *GetWellKnownCatalogRequest, opts ...grpc.CallOption) (*GetWellKnownCatalogResponse, error)
}

type aIFinderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIFinderServiceClient(cc grpc.ClientConnInterface) AIFinderServiceClient {
	return &aIFinderServiceClient{cc}
}

func (c *aIFinderServiceClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, AIFinderService_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIFinderServiceClient) GetWellKnownCatalog(ctx context.Context, in *GetWellKnownCatalogRequest, opts ...grpc.CallOption) (*GetWellKnownCatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWellKnownCatalogResponse)
	err := c.cc.Invoke(ctx, AIFinderService_GetWellKnownCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIFinderServiceServer is the server API for AIFinderService service.
// All implementations should embed UnimplementedAIFinderServiceServer
// for forward compatibility.
//
// AIFinderService is the federated AI Finder discovery surface over the AI
// Catalog model. It is exposed over gRPC and, via grpc-gateway, as a REST API.
type AIFinderServiceServer interface {
	// ListAgents returns catalog entries with deterministic, cacheable browsing
	// semantics (database filtering, no relevance ranking).
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	// GetWellKnownCatalog returns the AI Catalog well-known document (host
	// descriptor, published entries, and dynamic collections) at the RFC 8615 URI.
	GetWellKnownCatalog(context.Context, *GetWellKnownCatalogRequest) (*GetWellKnownCatalogResponse, error)
}

// UnimplementedAIFinderServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIFinderServiceServer struct{}

func (UnimplementedAIFinderServiceServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedAIFinderServiceServer) GetWellKnownCatalog(context.Context, *GetWellKnownCatalogRequest) (*GetWellKnownCatalogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWellKnownCatalog not implemented")
}
func (UnimplementedAIFinderServiceServer) testEmbeddedByValue() {}

// UnsafeAIFinderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIFinderServiceServer will
// result in compilation errors.
type UnsafeAIFinderServiceServer interface {
	mustEmbedUnimplementedAIFinderServiceServer()
}

func RegisterAIFinderServiceServer(s grpc.ServiceRegistrar, srv AIFinderServiceServer) {
	// If the following call pancis, it indicates UnimplementedAIFinderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIFinderService_ServiceDesc, srv)
}

func _AIFinderService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIFinderServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIFinderService_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIFinderServiceServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIFinderService_GetWellKnownCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWellKnownCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIFinderServiceServer).GetWellKnownCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIFinderService_GetWellKnownCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIFinderServiceServer).GetWellKnownCatalog(ctx, req.(*GetWellKnownCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIFinderService_ServiceDesc is the grpc.ServiceDesc for AIFinderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIFinderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agntcy.dir.catalog.v1.AIFinderService",
	HandlerType: (*AIFinderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAgents",
			Handler:    _AIFinderService_ListAgents_Handler,
		},
		{
			MethodName: "GetWellKnownCatalog",
			Handler:    _AIFinderService_GetWellKnownCatalog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agntcy/dir/catalog/v1/ai_finder_service.proto",
}
