# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

# Dirctl configuration for cluster2 to interact with cluster1's dir server
# This demonstrates cross-cluster federation functionality

failedJobsHistoryLimit: 10
successfulJobsHistoryLimit: 10
concurrencyPolicy: "Forbid"
schedule: "* * * * *"  # Run every 5 minutes to avoid overwhelming

image:
  repository: ghcr.io/agntcy/dir-ctl
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

args:
  - "push"
  - "/examples/record.json"
  - "--spiffe-socket-path"
  - "unix:/run/spire/sockets/spire-agent.sock"
  - "--server-addr"
  - "dir-cluster1-apiserver.dir-server.svc.cluster.local:8888"  # Connect to cluster1

# Environment variables for federation
env:
  - name: DIRECTORY_CLIENT_SPIFFE_TRUST_DOMAIN
    value: "cluster1.agntcy.org"  # Target cluster's trust domain

configMaps:
  - name: cluster2-federation-record
    data:
      record.json: |
        {
          "name": "directory.agntcy.org/cluster2/federation-test-agent",
          "version": "v1.0.0",
          "schema_version": "v0.5.0",
          "description": "Federation test agent from cluster2 pushing to cluster1.",
          "authors": ["AGNTCY Federation Team"],
          "created_at": "2025-08-14T12:00:00Z",
          "annotations": {
            "federation.source": "cluster2.agntcy.org",
            "federation.target": "cluster1.agntcy.org",
            "test.scenario": "cross-cluster-push"
          },
          "skills": [
            {
              "name": "Federation/Cross-Cluster Communication",
              "id": 50003
            },
            {
              "name": "Identity/SPIFFE Authentication",
              "id": 50004
            }
          ],
          "locators": [
            {
              "type": "docker-image",
              "url": "https://ghcr.io/agntcy/federation-test-agent-cluster2"
            }
          ],
          "domains": [
            {
              "name": "federation-testing"
            }
          ],
          "extensions": [
            {
              "name": "license",
              "version": "v1.0.0",
              "data": {
                "header": "Copyright (c) 2025 AGNTCY and/or its affiliates.",
                "license": "Apache-2.0"
              }
            },
            {
              "name": "schema.oasf.agntcy.org/features/federation",
              "version": "v1.0.0",
              "data": {
                "source_trust_domain": "cluster2.agntcy.org",
                "target_trust_domain": "cluster1.agntcy.org",
                "federation_type": "cross-cluster"
              }
            }
          ]
        }

serviceAccount:
  create: false

securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  readOnlyRootFilesystem: true

volumes:
  - name: spiffe-workload-api
    csi:
      driver: csi.spiffe.io
      readOnly: true
  - name: record-json
    configMap:
      name: cluster2-federation-record
      items:
        - key: record.json
          path: examples/record.json

volumeMounts:
  - name: spiffe-workload-api
    mountPath: /run/spire/sockets
    readOnly: true
  - name: record-json
    mountPath: /examples/record.json
    subPath: examples/record.json
    readOnly: true
