failedJobsHistoryLimit: 10
successfulJobsHistoryLimit: 10
concurrencyPolicy: "Forbid"
schedule: "* * * * *"

image:
  repository: ghcr.io/agntcy/dir-ctl
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

args:
  - "search"
  - "--limit"
  - "10"
  - "--offset" 
  - "0"
  - "--server-addr"
  - "dir-apiserver.default.svc.cluster.local:8888"

serviceAccount:
  create: false

securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  readOnlyRootFilesystem: true
