# Job config
failedJobsHistoryLimit: 10
successfulJobsHistoryLimit: 10
concurrencyPolicy: "Forbid"
schedule: "* * * * *" # every minute

# Configure the dirctl image (update tag as needed)
image:
  repository: ghcr.io/agntcy/dir-ctl
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

# Search command arguments
args:
  - "search"
  - "--limit"
  - "10"
  - "--offset" 
  - "0"
  - "--server-addr"
  - 'dir-apiserver.default.svc.cluster.local:8888'
  - "--spiffe-socket-path"
  - "unix:/spire-workload-api/spire-agent.sock"
  - "--spiffe-trust-domain"
  - "a-org.local"

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  readOnlyRootFilesystem: true

volumes:
  - name: agent
    csi:
      driver: b.csi.spiffe.io
      readOnly: true

volumeMounts:
  - name: agent
    mountPath: /spire-workload-api
    readOnly: true

######################################################################
### SPIFFEEEE
######################################################################
global:
  openshift: false
  spire:
    recommendations:
      enabled: true
    namespaces:
      create: false
    ingressControllerType: ingress-nginx
    clusterName: b
    trustDomain: b-org.local
    bundleConfigMap: spire-bundle-b
    caSubject:
      country: US
      organization: B
      commonName: b.local

spire-server:
  federation:
    enabled: true
    ingress:
      enabled: true
  controllerManager:
    identities:
      clusterSPIFFEIDs:
        default:
          federatesWith:
          - a-org.local
      clusterFederatedTrustDomains:
        a:
          bundleEndpointProfile:
            endpointSPIFFEID: spiffe://a-org.local/spire/server
            type: https_spiffe
          bundleEndpointURL: https://spire-server-federation.a-org.local
          trustDomain: a-org.local

spiffe-oidc-discovery-provider:
  enabled: true
  tls:
    spire:
      enabled: false
  csiDriverName: b.csi.spiffe.io
  ingress:
    enabled: true

spire-agent:
  healthChecks:
    port: 9983
  telemetry:
    prometheus:
      port: 9990
  socketPath: /run/spire/agent-sockets-b/spire-agent.sock

spiffe-csi-driver:
  healthChecks:
    port: 9811
  pluginName: b.csi.spiffe.io
  agentSocketPath: /run/spire/agent-sockets-b/spire-agent.sock
