failedJobsHistoryLimit: 10
successfulJobsHistoryLimit: 10
concurrencyPolicy: "Forbid"
schedule: "* * * * *"

image:
  repository: ghcr.io/agntcy/dir-ctl
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

args:
  - "search"
  - "--limit"
  - "10"
  - "--offset"
  - "0"
  - "--spiffe-socket-path"
  - "unix:/run/spire/sockets/agent.sock"
  - "--spiffe-trust-domain"
  - "example.org"
  - "--server-addr"
  - "dir-apiserver.dir-server.svc.cluster.local:8888"

serviceAccount:
  create: false

securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  readOnlyRootFilesystem: true

volumes:
  - name: spire-agent-socket
    hostPath:
      path: /run/spire/sockets
      type: Directory

volumeMounts:
  - name: spire-agent-socket
    mountPath: /run/spire/sockets
    readOnly: true
