failedJobsHistoryLimit: 10
successfulJobsHistoryLimit: 10
concurrencyPolicy: "Forbid"
schedule: "* * * * *"

image:
  repository: ghcr.io/agntcy/dir-ctl
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

args:
  - "search"
  - "--limit"
  - "10"
  - "--offset"
  - "0"
  - "--spiffe-socket-path"
  - "unix:/run/spire/sockets/spire-agent.sock"
  - "--server-addr"
  - "dir-apiserver.dir-server.svc.cluster.local:8888"

# Additional environment variables
env:
  - name: DIRECTORY_CLIENT_SPIFFE_TRUST_DOMAIN
    value: "example.org"

serviceAccount:
  create: false

securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  readOnlyRootFilesystem: true

volumes:
  - name: spiffe-workload-api
    csi:
      driver: csi.spiffe.io
      readOnly: true

volumeMounts:
  - name: spiffe-workload-api
    mountPath: /run/spire/sockets
    readOnly: true
