// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: routing/v1alpha2/query.proto

package routingv1alpha2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// List of supported query types.
type AgentRecordQuery_Type int32

const (
	AgentRecordQuery_TYPE_UNSPECIFIED AgentRecordQuery_Type = 0
	AgentRecordQuery_TYPE_SKILL       AgentRecordQuery_Type = 1
	AgentRecordQuery_TYPE_LOCATOR     AgentRecordQuery_Type = 2
)

// Enum value maps for AgentRecordQuery_Type.
var (
	AgentRecordQuery_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_SKILL",
		2: "TYPE_LOCATOR",
	}
	AgentRecordQuery_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_SKILL":       1,
		"TYPE_LOCATOR":     2,
	}
)

func (x AgentRecordQuery_Type) Enum() *AgentRecordQuery_Type {
	p := new(AgentRecordQuery_Type)
	*p = x
	return p
}

func (x AgentRecordQuery_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentRecordQuery_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_routing_v1alpha2_query_proto_enumTypes[0].Descriptor()
}

func (AgentRecordQuery_Type) Type() protoreflect.EnumType {
	return &file_routing_v1alpha2_query_proto_enumTypes[0]
}

func (x AgentRecordQuery_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentRecordQuery_Type.Descriptor instead.
func (AgentRecordQuery_Type) EnumDescriptor() ([]byte, []int) {
	return file_routing_v1alpha2_query_proto_rawDescGZIP(), []int{0, 0}
}

// A query to match the agent record against during discovery.
// For example:
//
//	{ type: TYPE_SKILL, value: "Natural Language Processing" }
//	{ type: TYPE_LOCATOR, value: "helm-chart" }
type AgentRecordQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of the query to match against.
	Type AgentRecordQuery_Type `protobuf:"varint,1,opt,name=type,proto3,enum=routing.v1alpha2.AgentRecordQuery_Type" json:"type,omitempty"`
	// The query value to match against.
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRecordQuery) Reset() {
	*x = AgentRecordQuery{}
	mi := &file_routing_v1alpha2_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRecordQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRecordQuery) ProtoMessage() {}

func (x *AgentRecordQuery) ProtoReflect() protoreflect.Message {
	mi := &file_routing_v1alpha2_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRecordQuery.ProtoReflect.Descriptor instead.
func (*AgentRecordQuery) Descriptor() ([]byte, []int) {
	return file_routing_v1alpha2_query_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRecordQuery) GetType() AgentRecordQuery_Type {
	if x != nil {
		return x.Type
	}
	return AgentRecordQuery_TYPE_UNSPECIFIED
}

func (x *AgentRecordQuery) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_routing_v1alpha2_query_proto protoreflect.FileDescriptor

var file_routing_v1alpha2_query_proto_rawDesc = string([]byte{
	0x0a, 0x1c, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x32, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32,
	0x22, 0xa5, 0x01, 0x0a, 0x10, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x3b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3e, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53,
	0x4b, 0x49, 0x4c, 0x4c, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4c,
	0x4f, 0x43, 0x41, 0x54, 0x4f, 0x52, 0x10, 0x02, 0x42, 0xbf, 0x01, 0x0a, 0x14, 0x63, 0x6f, 0x6d,
	0x2e, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x32, 0x42, 0x0a, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x67, 0x6e, 0x74,
	0x63, 0x79, 0x2f, 0x64, 0x69, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x69,
	0x6e, 0x67, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x3b, 0x72, 0x6f, 0x75, 0x74,
	0x69, 0x6e, 0x67, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0xa2, 0x02, 0x03, 0x52, 0x58,
	0x58, 0xaa, 0x02, 0x10, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x56, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x32, 0xca, 0x02, 0x10, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x5c, 0x56,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0xe2, 0x02, 0x1c, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e,
	0x67, 0x5c, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67,
	0x3a, 0x3a, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_routing_v1alpha2_query_proto_rawDescOnce sync.Once
	file_routing_v1alpha2_query_proto_rawDescData []byte
)

func file_routing_v1alpha2_query_proto_rawDescGZIP() []byte {
	file_routing_v1alpha2_query_proto_rawDescOnce.Do(func() {
		file_routing_v1alpha2_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routing_v1alpha2_query_proto_rawDesc), len(file_routing_v1alpha2_query_proto_rawDesc)))
	})
	return file_routing_v1alpha2_query_proto_rawDescData
}

var file_routing_v1alpha2_query_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_routing_v1alpha2_query_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_routing_v1alpha2_query_proto_goTypes = []any{
	(AgentRecordQuery_Type)(0), // 0: routing.v1alpha2.AgentRecordQuery.Type
	(*AgentRecordQuery)(nil),   // 1: routing.v1alpha2.AgentRecordQuery
}
var file_routing_v1alpha2_query_proto_depIdxs = []int32{
	0, // 0: routing.v1alpha2.AgentRecordQuery.type:type_name -> routing.v1alpha2.AgentRecordQuery.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_routing_v1alpha2_query_proto_init() }
func file_routing_v1alpha2_query_proto_init() {
	if File_routing_v1alpha2_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routing_v1alpha2_query_proto_rawDesc), len(file_routing_v1alpha2_query_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_routing_v1alpha2_query_proto_goTypes,
		DependencyIndexes: file_routing_v1alpha2_query_proto_depIdxs,
		EnumInfos:         file_routing_v1alpha2_query_proto_enumTypes,
		MessageInfos:      file_routing_v1alpha2_query_proto_msgTypes,
	}.Build()
	File_routing_v1alpha2_query_proto = out.File
	file_routing_v1alpha2_query_proto_goTypes = nil
	file_routing_v1alpha2_query_proto_depIdxs = nil
}
