// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/naming/v1/name_verification.proto (package agntcy.dir.naming.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file agntcy/dir/naming/v1/name_verification.proto.
 */
export declare const file_agntcy_dir_naming_v1_name_verification: GenFile;

/**
 * Verification represents the result of verifying that a record's
 * signing key is authorized by the domain claimed in the record's name.
 *
 * @generated from message agntcy.dir.naming.v1.Verification
 */
export declare type Verification = Message<"agntcy.dir.naming.v1.Verification"> & {
  /**
   * The domain that was verified (e.g., "cisco.com").
   *
   * @generated from field: string domain = 1;
   */
  domain: string;

  /**
   * The verification method used: "dns" or "wellknown".
   *
   * @generated from field: string method = 2;
   */
  method: string;

  /**
   * The ID of the key that matched the signing key.
   *
   * @generated from field: string matched_key_id = 3;
   */
  matchedKeyId: string;

  /**
   * When the verification was performed.
   *
   * @generated from field: google.protobuf.Timestamp verified_at = 4;
   */
  verifiedAt?: Timestamp;
};

/**
 * Describes the message agntcy.dir.naming.v1.Verification.
 * Use `create(VerificationSchema)` to create a new message.
 */
export declare const VerificationSchema: GenMessage<Verification>;

