// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/naming/v1/naming_service.proto (package agntcy.dir.naming.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { DomainVerification } from "./domain_verification_pb.js";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file agntcy/dir/naming/v1/naming_service.proto.
 */
export declare const file_agntcy_dir_naming_v1_naming_service: GenFile;

/**
 * VerifyDomainRequest is the request for performing domain verification.
 *
 * @generated from message agntcy.dir.naming.v1.VerifyDomainRequest
 */
export declare type VerifyDomainRequest = Message<"agntcy.dir.naming.v1.VerifyDomainRequest"> & {
  /**
   * The CID of the signed record to verify.
   *
   * @generated from field: string cid = 1;
   */
  cid: string;
};

/**
 * Describes the message agntcy.dir.naming.v1.VerifyDomainRequest.
 * Use `create(VerifyDomainRequestSchema)` to create a new message.
 */
export declare const VerifyDomainRequestSchema: GenMessage<VerifyDomainRequest>;

/**
 * VerifyDomainResponse is the response for domain verification.
 *
 * @generated from message agntcy.dir.naming.v1.VerifyDomainResponse
 */
export declare type VerifyDomainResponse = Message<"agntcy.dir.naming.v1.VerifyDomainResponse"> & {
  /**
   * Whether the domain verification succeeded.
   *
   * @generated from field: bool verified = 1;
   */
  verified: boolean;

  /**
   * The domain verification details (only set if verified is true).
   *
   * @generated from field: agntcy.dir.naming.v1.DomainVerification verification = 2;
   */
  verification?: DomainVerification;

  /**
   * Error message if verification failed.
   *
   * @generated from field: optional string error_message = 3;
   */
  errorMessage?: string;
};

/**
 * Describes the message agntcy.dir.naming.v1.VerifyDomainResponse.
 * Use `create(VerifyDomainResponseSchema)` to create a new message.
 */
export declare const VerifyDomainResponseSchema: GenMessage<VerifyDomainResponse>;

/**
 * CheckDomainVerificationRequest is the request for checking domain verification.
 *
 * @generated from message agntcy.dir.naming.v1.CheckDomainVerificationRequest
 */
export declare type CheckDomainVerificationRequest = Message<"agntcy.dir.naming.v1.CheckDomainVerificationRequest"> & {
  /**
   * The CID of the record to check.
   *
   * @generated from field: string cid = 1;
   */
  cid: string;
};

/**
 * Describes the message agntcy.dir.naming.v1.CheckDomainVerificationRequest.
 * Use `create(CheckDomainVerificationRequestSchema)` to create a new message.
 */
export declare const CheckDomainVerificationRequestSchema: GenMessage<CheckDomainVerificationRequest>;

/**
 * CheckDomainVerificationResponse is the response for checking domain verification.
 *
 * @generated from message agntcy.dir.naming.v1.CheckDomainVerificationResponse
 */
export declare type CheckDomainVerificationResponse = Message<"agntcy.dir.naming.v1.CheckDomainVerificationResponse"> & {
  /**
   * Whether the record has verified domain ownership.
   *
   * @generated from field: bool verified = 1;
   */
  verified: boolean;

  /**
   * The domain verification details (only set if verified is true).
   *
   * @generated from field: agntcy.dir.naming.v1.DomainVerification verification = 2;
   */
  verification?: DomainVerification;

  /**
   * Error message if verification lookup failed.
   *
   * @generated from field: optional string error_message = 3;
   */
  errorMessage?: string;
};

/**
 * Describes the message agntcy.dir.naming.v1.CheckDomainVerificationResponse.
 * Use `create(CheckDomainVerificationResponseSchema)` to create a new message.
 */
export declare const CheckDomainVerificationResponseSchema: GenMessage<CheckDomainVerificationResponse>;

/**
 * ListVerifiedAgentsRequest is the request for listing verified agents.
 *
 * @generated from message agntcy.dir.naming.v1.ListVerifiedAgentsRequest
 */
export declare type ListVerifiedAgentsRequest = Message<"agntcy.dir.naming.v1.ListVerifiedAgentsRequest"> & {
  /**
   * The domain to list verified agents for (e.g., "cisco.com").
   *
   * @generated from field: string domain = 1;
   */
  domain: string;

  /**
   * Maximum number of results to return (default: 100).
   *
   * @generated from field: int32 limit = 2;
   */
  limit: number;

  /**
   * Pagination token for fetching the next page.
   *
   * @generated from field: string page_token = 3;
   */
  pageToken: string;
};

/**
 * Describes the message agntcy.dir.naming.v1.ListVerifiedAgentsRequest.
 * Use `create(ListVerifiedAgentsRequestSchema)` to create a new message.
 */
export declare const ListVerifiedAgentsRequestSchema: GenMessage<ListVerifiedAgentsRequest>;

/**
 * ListVerifiedAgentsResponse is the response for listing verified agents.
 *
 * @generated from message agntcy.dir.naming.v1.ListVerifiedAgentsResponse
 */
export declare type ListVerifiedAgentsResponse = Message<"agntcy.dir.naming.v1.ListVerifiedAgentsResponse"> & {
  /**
   * The list of verified agents for the domain.
   *
   * @generated from field: repeated agntcy.dir.naming.v1.VerifiedAgent agents = 1;
   */
  agents: VerifiedAgent[];

  /**
   * Token for fetching the next page of results.
   *
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message agntcy.dir.naming.v1.ListVerifiedAgentsResponse.
 * Use `create(ListVerifiedAgentsResponseSchema)` to create a new message.
 */
export declare const ListVerifiedAgentsResponseSchema: GenMessage<ListVerifiedAgentsResponse>;

/**
 * VerifiedAgent represents an agent that has verified domain ownership.
 *
 * @generated from message agntcy.dir.naming.v1.VerifiedAgent
 */
export declare type VerifiedAgent = Message<"agntcy.dir.naming.v1.VerifiedAgent"> & {
  /**
   * The CID of the verified record.
   *
   * @generated from field: string cid = 1;
   */
  cid: string;

  /**
   * The full name of the agent (e.g., "cisco.com/marketing-agent").
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * The version of the agent.
   *
   * @generated from field: string version = 3;
   */
  version: string;

  /**
   * When the domain was verified.
   *
   * @generated from field: google.protobuf.Timestamp verified_at = 4;
   */
  verifiedAt?: Timestamp;

  /**
   * The verification method used.
   *
   * @generated from field: string method = 5;
   */
  method: string;
};

/**
 * Describes the message agntcy.dir.naming.v1.VerifiedAgent.
 * Use `create(VerifiedAgentSchema)` to create a new message.
 */
export declare const VerifiedAgentSchema: GenMessage<VerifiedAgent>;

/**
 * NamingService provides methods to check domain verification status
 * and list verified agents for a domain.
 *
 * @generated from service agntcy.dir.naming.v1.NamingService
 */
export declare const NamingService: GenService<{
  /**
   * VerifyDomain performs domain ownership verification for a signed record.
   * This should be called after signing a record to verify and store the domain ownership proof.
   *
   * @generated from rpc agntcy.dir.naming.v1.NamingService.VerifyDomain
   */
  verifyDomain: {
    methodKind: "unary";
    input: typeof VerifyDomainRequestSchema;
    output: typeof VerifyDomainResponseSchema;
  },
  /**
   * CheckDomainVerification checks if a record has verified domain ownership.
   *
   * @generated from rpc agntcy.dir.naming.v1.NamingService.CheckDomainVerification
   */
  checkDomainVerification: {
    methodKind: "unary";
    input: typeof CheckDomainVerificationRequestSchema;
    output: typeof CheckDomainVerificationResponseSchema;
  },
  /**
   * ListVerifiedAgents lists all agents that have verified domain ownership for a given domain.
   *
   * @generated from rpc agntcy.dir.naming.v1.NamingService.ListVerifiedAgents
   */
  listVerifiedAgents: {
    methodKind: "unary";
    input: typeof ListVerifiedAgentsRequestSchema;
    output: typeof ListVerifiedAgentsResponseSchema;
  },
}>;

