// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/naming/v1/naming_service.proto (package agntcy.dir.naming.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { DomainVerification } from "./domain_verification_pb.js";

/**
 * Describes the file agntcy/dir/naming/v1/naming_service.proto.
 */
export declare const file_agntcy_dir_naming_v1_naming_service: GenFile;

/**
 * VerifyRequest is the request for performing name verification.
 *
 * @generated from message agntcy.dir.naming.v1.VerifyRequest
 */
export declare type VerifyRequest = Message<"agntcy.dir.naming.v1.VerifyRequest"> & {
  /**
   * The CID of the signed record to verify.
   *
   * @generated from field: string cid = 1;
   */
  cid: string;
};

/**
 * Describes the message agntcy.dir.naming.v1.VerifyRequest.
 * Use `create(VerifyRequestSchema)` to create a new message.
 */
export declare const VerifyRequestSchema: GenMessage<VerifyRequest>;

/**
 * VerifyResponse is the response for name verification.
 *
 * @generated from message agntcy.dir.naming.v1.VerifyResponse
 */
export declare type VerifyResponse = Message<"agntcy.dir.naming.v1.VerifyResponse"> & {
  /**
   * Whether the name verification succeeded.
   *
   * @generated from field: bool verified = 1;
   */
  verified: boolean;

  /**
   * The verification details (only set if verified is true).
   *
   * @generated from field: agntcy.dir.naming.v1.DomainVerification verification = 2;
   */
  verification?: DomainVerification;

  /**
   * Error message if verification failed.
   *
   * @generated from field: optional string error_message = 3;
   */
  errorMessage?: string;
};

/**
 * Describes the message agntcy.dir.naming.v1.VerifyResponse.
 * Use `create(VerifyResponseSchema)` to create a new message.
 */
export declare const VerifyResponseSchema: GenMessage<VerifyResponse>;

/**
 * GetVerificationInfoRequest is the request for retrieving verification info.
 *
 * @generated from message agntcy.dir.naming.v1.GetVerificationInfoRequest
 */
export declare type GetVerificationInfoRequest = Message<"agntcy.dir.naming.v1.GetVerificationInfoRequest"> & {
  /**
   * The CID of the record to check.
   *
   * @generated from field: string cid = 1;
   */
  cid: string;
};

/**
 * Describes the message agntcy.dir.naming.v1.GetVerificationInfoRequest.
 * Use `create(GetVerificationInfoRequestSchema)` to create a new message.
 */
export declare const GetVerificationInfoRequestSchema: GenMessage<GetVerificationInfoRequest>;

/**
 * GetVerificationInfoResponse is the response for retrieving verification info.
 *
 * @generated from message agntcy.dir.naming.v1.GetVerificationInfoResponse
 */
export declare type GetVerificationInfoResponse = Message<"agntcy.dir.naming.v1.GetVerificationInfoResponse"> & {
  /**
   * Whether the record has verified name ownership.
   *
   * @generated from field: bool verified = 1;
   */
  verified: boolean;

  /**
   * The verification details (only set if verified is true).
   *
   * @generated from field: agntcy.dir.naming.v1.DomainVerification verification = 2;
   */
  verification?: DomainVerification;

  /**
   * Error message if lookup failed.
   *
   * @generated from field: optional string error_message = 3;
   */
  errorMessage?: string;
};

/**
 * Describes the message agntcy.dir.naming.v1.GetVerificationInfoResponse.
 * Use `create(GetVerificationInfoResponseSchema)` to create a new message.
 */
export declare const GetVerificationInfoResponseSchema: GenMessage<GetVerificationInfoResponse>;

/**
 * NamingService provides methods to verify and inspect name verification state.
 *
 * @generated from service agntcy.dir.naming.v1.NamingService
 */
export declare const NamingService: GenService<{
  /**
   * Verify performs name verification for a signed record.
   * The record's name should be prefixed with the protocol (dns:// or wellknown://)
   * to indicate the verification method.
   *
   * @generated from rpc agntcy.dir.naming.v1.NamingService.Verify
   */
  verify: {
    methodKind: "unary";
    input: typeof VerifyRequestSchema;
    output: typeof VerifyResponseSchema;
  },
  /**
   * GetVerificationInfo retrieves the verification info for a record.
   *
   * @generated from rpc agntcy.dir.naming.v1.NamingService.GetVerificationInfo
   */
  getVerificationInfo: {
    methodKind: "unary";
    input: typeof GetVerificationInfoRequestSchema;
    output: typeof GetVerificationInfoResponseSchema;
  },
}>;

