// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/sign/v1/sign_service.proto (package agntcy.dir.sign.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { RecordRef } from "../../core/v1/record_pb.js";
import type { Signature } from "./signature_pb.js";

/**
 * Describes the file agntcy/dir/sign/v1/sign_service.proto.
 */
export declare const file_agntcy_dir_sign_v1_sign_service: GenFile;

/**
 * @generated from message agntcy.dir.sign.v1.SignRequest
 */
export declare type SignRequest = Message<"agntcy.dir.sign.v1.SignRequest"> & {
  /**
   * Record reference to be signed
   *
   * @generated from field: agntcy.dir.core.v1.RecordRef record_ref = 1;
   */
  recordRef?: RecordRef;

  /**
   * Signing provider to use
   *
   * @generated from field: agntcy.dir.sign.v1.SignRequestProvider provider = 2;
   */
  provider?: SignRequestProvider;
};

/**
 * Describes the message agntcy.dir.sign.v1.SignRequest.
 * Use `create(SignRequestSchema)` to create a new message.
 */
export declare const SignRequestSchema: GenMessage<SignRequest>;

/**
 * @generated from message agntcy.dir.sign.v1.SignRequestProvider
 */
export declare type SignRequestProvider = Message<"agntcy.dir.sign.v1.SignRequestProvider"> & {
  /**
   * @generated from oneof agntcy.dir.sign.v1.SignRequestProvider.request
   */
  request: {
    /**
     * Sign with OIDC provider
     *
     * @generated from field: agntcy.dir.sign.v1.SignWithOIDC oidc = 1;
     */
    value: SignWithOIDC;
    case: "oidc";
  } | {
    /**
     * Sign with PEM-encoded public key
     *
     * @generated from field: agntcy.dir.sign.v1.SignWithKey key = 2;
     */
    value: SignWithKey;
    case: "key";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message agntcy.dir.sign.v1.SignRequestProvider.
 * Use `create(SignRequestProviderSchema)` to create a new message.
 */
export declare const SignRequestProviderSchema: GenMessage<SignRequestProvider>;

/**
 * @generated from message agntcy.dir.sign.v1.SignWithOIDC
 */
export declare type SignWithOIDC = Message<"agntcy.dir.sign.v1.SignWithOIDC"> & {
  /**
   * Token for OIDC provider
   *
   * @generated from field: string id_token = 1;
   */
  idToken: string;

  /**
   * Signing options for OIDC
   *
   * @generated from field: agntcy.dir.sign.v1.SignWithOIDC.SignOpts options = 2;
   */
  options?: SignWithOIDC_SignOpts;
};

/**
 * Describes the message agntcy.dir.sign.v1.SignWithOIDC.
 * Use `create(SignWithOIDCSchema)` to create a new message.
 */
export declare const SignWithOIDCSchema: GenMessage<SignWithOIDC>;

/**
 * List of sign options for OIDC
 *
 * @generated from message agntcy.dir.sign.v1.SignWithOIDC.SignOpts
 */
export declare type SignWithOIDC_SignOpts = Message<"agntcy.dir.sign.v1.SignWithOIDC.SignOpts"> & {
  /**
   * Fulcio authority access URL (default value: https://fulcio.sigstage.dev)
   *
   * @generated from field: optional string fulcio_url = 1;
   */
  fulcioUrl?: string;

  /**
   * Rekor validator access URL (default value: https://rekor.sigstage.dev)
   *
   * @generated from field: optional string rekor_url = 2;
   */
  rekorUrl?: string;

  /**
   * Timestamp authority access URL (default value: https://timestamp.sigstage.dev/api/v1/timestamp)
   *
   * @generated from field: optional string timestamp_url = 3;
   */
  timestampUrl?: string;

  /**
   * OIDC provider access URL (default value: https://oauth2.sigstage.dev/auth)
   *
   * @generated from field: optional string oidc_provider_url = 4;
   */
  oidcProviderUrl?: string;
};

/**
 * Describes the message agntcy.dir.sign.v1.SignWithOIDC.SignOpts.
 * Use `create(SignWithOIDC_SignOptsSchema)` to create a new message.
 */
export declare const SignWithOIDC_SignOptsSchema: GenMessage<SignWithOIDC_SignOpts>;

/**
 * @generated from message agntcy.dir.sign.v1.SignWithKey
 */
export declare type SignWithKey = Message<"agntcy.dir.sign.v1.SignWithKey"> & {
  /**
   * Private key used for signing
   *
   * @generated from field: bytes private_key = 1;
   */
  privateKey: Uint8Array;

  /**
   * Password to unlock the private key
   *
   * @generated from field: optional bytes password = 2;
   */
  password?: Uint8Array;
};

/**
 * Describes the message agntcy.dir.sign.v1.SignWithKey.
 * Use `create(SignWithKeySchema)` to create a new message.
 */
export declare const SignWithKeySchema: GenMessage<SignWithKey>;

/**
 * @generated from message agntcy.dir.sign.v1.SignResponse
 */
export declare type SignResponse = Message<"agntcy.dir.sign.v1.SignResponse"> & {
  /**
   * Cryptographic signature of the record
   *
   * @generated from field: agntcy.dir.sign.v1.Signature signature = 1;
   */
  signature?: Signature;
};

/**
 * Describes the message agntcy.dir.sign.v1.SignResponse.
 * Use `create(SignResponseSchema)` to create a new message.
 */
export declare const SignResponseSchema: GenMessage<SignResponse>;

/**
 * @generated from message agntcy.dir.sign.v1.VerifyRequest
 */
export declare type VerifyRequest = Message<"agntcy.dir.sign.v1.VerifyRequest"> & {
  /**
   * Record reference to be verified
   *
   * @generated from field: agntcy.dir.core.v1.RecordRef record_ref = 1;
   */
  recordRef?: RecordRef;

  /**
   * Optional verification options. If not provided, any valid signature is accepted.
   *
   * @generated from field: agntcy.dir.sign.v1.VerifyOptions options = 2;
   */
  options?: VerifyOptions;
};

/**
 * Describes the message agntcy.dir.sign.v1.VerifyRequest.
 * Use `create(VerifyRequestSchema)` to create a new message.
 */
export declare const VerifyRequestSchema: GenMessage<VerifyRequest>;

/**
 * Verification options - specifies what criteria to verify against
 *
 * @generated from message agntcy.dir.sign.v1.VerifyOptions
 */
export declare type VerifyOptions = Message<"agntcy.dir.sign.v1.VerifyOptions"> & {
  /**
   * @generated from oneof agntcy.dir.sign.v1.VerifyOptions.verification_type
   */
  verificationType: {
    /**
     * Verify against a specific public key
     *
     * @generated from field: agntcy.dir.sign.v1.VerifyWithPublicKey key = 1;
     */
    value: VerifyWithPublicKey;
    case: "key";
  } | {
    /**
     * Verify against OIDC identity
     *
     * @generated from field: agntcy.dir.sign.v1.VerifyWithOIDCIdentity oidc = 2;
     */
    value: VerifyWithOIDCIdentity;
    case: "oidc";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message agntcy.dir.sign.v1.VerifyOptions.
 * Use `create(VerifyOptionsSchema)` to create a new message.
 */
export declare const VerifyOptionsSchema: GenMessage<VerifyOptions>;

/**
 * Verify signature against a specific public key
 *
 * @generated from message agntcy.dir.sign.v1.VerifyWithPublicKey
 */
export declare type VerifyWithPublicKey = Message<"agntcy.dir.sign.v1.VerifyWithPublicKey"> & {
  /**
   * PEM-encoded public key to verify against
   *
   * @generated from field: string public_key = 1;
   */
  publicKey: string;
};

/**
 * Describes the message agntcy.dir.sign.v1.VerifyWithPublicKey.
 * Use `create(VerifyWithPublicKeySchema)` to create a new message.
 */
export declare const VerifyWithPublicKeySchema: GenMessage<VerifyWithPublicKey>;

/**
 * Verify signature against OIDC identity
 *
 * @generated from message agntcy.dir.sign.v1.VerifyWithOIDCIdentity
 */
export declare type VerifyWithOIDCIdentity = Message<"agntcy.dir.sign.v1.VerifyWithOIDCIdentity"> & {
  /**
   * OIDC issuer URL (exact match, e.g., "https://github.com/login/oauth")
   *
   * @generated from field: string issuer = 1;
   */
  issuer: string;

  /**
   * OIDC subject/identity (exact match, e.g., "user@example.com")
   *
   * @generated from field: string identity = 2;
   */
  identity: string;

  /**
   * Optional trust root configuration for verification.
   * If not provided, uses Sigstore public good instance.
   *
   * @generated from field: agntcy.dir.sign.v1.TrustRoot trust_root = 3;
   */
  trustRoot?: TrustRoot;
};

/**
 * Describes the message agntcy.dir.sign.v1.VerifyWithOIDCIdentity.
 * Use `create(VerifyWithOIDCIdentitySchema)` to create a new message.
 */
export declare const VerifyWithOIDCIdentitySchema: GenMessage<VerifyWithOIDCIdentity>;

/**
 * Trust root configuration for Sigstore verification
 *
 * @generated from message agntcy.dir.sign.v1.TrustRoot
 */
export declare type TrustRoot = Message<"agntcy.dir.sign.v1.TrustRoot"> & {
  /**
   * Fulcio CA root certificate (PEM-encoded).
   * If not provided, uses Sigstore public good Fulcio root.
   *
   * @generated from field: optional string fulcio_root_pem = 1;
   */
  fulcioRootPem?: string;

  /**
   * Rekor public key (PEM-encoded).
   * If not provided, uses Sigstore public good Rekor key.
   *
   * @generated from field: optional string rekor_public_key_pem = 2;
   */
  rekorPublicKeyPem?: string;

  /**
   * Timestamp authority root certificates (PEM-encoded).
   * If not provided, uses Sigstore public good TSA roots.
   *
   * @generated from field: repeated string timestamp_authority_roots_pem = 3;
   */
  timestampAuthorityRootsPem: string[];

  /**
   * Certificate Transparency log public keys (PEM-encoded).
   * If not provided, uses Sigstore public good CT log keys.
   *
   * @generated from field: repeated string ct_log_public_keys_pem = 4;
   */
  ctLogPublicKeysPem: string[];
};

/**
 * Describes the message agntcy.dir.sign.v1.TrustRoot.
 * Use `create(TrustRootSchema)` to create a new message.
 */
export declare const TrustRootSchema: GenMessage<TrustRoot>;

/**
 * @generated from message agntcy.dir.sign.v1.VerifyResponse
 */
export declare type VerifyResponse = Message<"agntcy.dir.sign.v1.VerifyResponse"> & {
  /**
   * The verify process result
   *
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * Optional error message if verification failed
   *
   * @generated from field: optional string error_message = 2;
   */
  errorMessage?: string;

  /**
   * Metadata about the signer (deprecated, use signers instead)
   * Common keys:
   * - "provider": "oidc" or "key"
   * - "oidc.issuer": OIDC issuer URL (OIDC provider only)
   * - "oidc.identity": OIDC identity/subject (OIDC provider only)
   * - "public_key": Public key used for verification (Key provider only)
   *
   * @generated from field: map<string, string> signer_metadata = 3;
   */
  signerMetadata: { [key: string]: string };

  /**
   * List of all signers that signed the record
   * Each entry represents one valid signature on the record
   *
   * @generated from field: repeated agntcy.dir.sign.v1.SignerInfo signers = 4;
   */
  signers: SignerInfo[];
};

/**
 * Describes the message agntcy.dir.sign.v1.VerifyResponse.
 * Use `create(VerifyResponseSchema)` to create a new message.
 */
export declare const VerifyResponseSchema: GenMessage<VerifyResponse>;

/**
 * Structured information about who signed the record
 *
 * @generated from message agntcy.dir.sign.v1.SignerInfo
 */
export declare type SignerInfo = Message<"agntcy.dir.sign.v1.SignerInfo"> & {
  /**
   * @generated from oneof agntcy.dir.sign.v1.SignerInfo.signer_type
   */
  signerType: {
    /**
     * Key-based signer information
     *
     * @generated from field: agntcy.dir.sign.v1.KeySignerInfo key = 1;
     */
    value: KeySignerInfo;
    case: "key";
  } | {
    /**
     * OIDC-based signer information
     *
     * @generated from field: agntcy.dir.sign.v1.OIDCSignerInfo oidc = 2;
     */
    value: OIDCSignerInfo;
    case: "oidc";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message agntcy.dir.sign.v1.SignerInfo.
 * Use `create(SignerInfoSchema)` to create a new message.
 */
export declare const SignerInfoSchema: GenMessage<SignerInfo>;

/**
 * Information about a key-based signer
 *
 * @generated from message agntcy.dir.sign.v1.KeySignerInfo
 */
export declare type KeySignerInfo = Message<"agntcy.dir.sign.v1.KeySignerInfo"> & {
  /**
   * Public key used for verification (PEM-encoded)
   *
   * @generated from field: string public_key = 1;
   */
  publicKey: string;

  /**
   * Key algorithm (e.g., "ECDSA-P256", "Ed25519", "RSA")
   *
   * @generated from field: string algorithm = 2;
   */
  algorithm: string;
};

/**
 * Describes the message agntcy.dir.sign.v1.KeySignerInfo.
 * Use `create(KeySignerInfoSchema)` to create a new message.
 */
export declare const KeySignerInfoSchema: GenMessage<KeySignerInfo>;

/**
 * Information about an OIDC-based signer
 *
 * @generated from message agntcy.dir.sign.v1.OIDCSignerInfo
 */
export declare type OIDCSignerInfo = Message<"agntcy.dir.sign.v1.OIDCSignerInfo"> & {
  /**
   * OIDC issuer URL (e.g., "https://github.com/login/oauth")
   *
   * @generated from field: string issuer = 1;
   */
  issuer: string;

  /**
   * OIDC subject/identity (e.g., "user@example.com")
   *
   * @generated from field: string identity = 2;
   */
  identity: string;
};

/**
 * Describes the message agntcy.dir.sign.v1.OIDCSignerInfo.
 * Use `create(OIDCSignerInfoSchema)` to create a new message.
 */
export declare const OIDCSignerInfoSchema: GenMessage<OIDCSignerInfo>;

/**
 * SignService provides methods to sign and verify records.
 *
 * @generated from service agntcy.dir.sign.v1.SignService
 */
export declare const SignService: GenService<{
  /**
   * Sign record using keyless OIDC based provider or using PEM-encoded private key with an optional passphrase
   *
   * @generated from rpc agntcy.dir.sign.v1.SignService.Sign
   */
  sign: {
    methodKind: "unary";
    input: typeof SignRequestSchema;
    output: typeof SignResponseSchema;
  },
  /**
   * Verify signed record using keyless OIDC based provider or using PEM-encoded formatted PEM public key encrypted
   *
   * @generated from rpc agntcy.dir.sign.v1.SignService.Verify
   */
  verify: {
    methodKind: "unary";
    input: typeof VerifyRequestSchema;
    output: typeof VerifyResponseSchema;
  },
}>;

