global:
  spire:
    clusterName: test-cluster
    trustDomain: test.org
    caSubject:
      country: US
      organization: TestORG
      commonName: test.org

spiffe-oidc-discovery-provider:
  enabled: true
  tls:
    spire:
      enabled: false
  csiDriverName: csi.spiffe.io
  ingress:
    enabled: true

spire-agent:
  socketPath: /run/spire/sockets/spire-agent.sock

spiffe-csi-driver:
  pluginName: csi.spiffe.io
  agentSocketPath: /run/spire/sockets/spire-agent.sock
