# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

# SPIRE Federation Configuration for Cluster 1 (Primary Trust Domain)
global:
  spire:
    recommendations:
      enabled: true
    clusterName: federation-cluster1
    trustDomain: cluster1.agntcy.org
    caSubject:
      country: US
      organization: AGNTCY
      commonName: cluster1.agntcy.org

spire-server:
  federation:
    enabled: true
    ingress:
      enabled: true
  controllerManager:
    identities:
      clusterSPIFFEIDs:
        default:
          federatesWith:
          - cluster2.agntcy.org
      clusterFederatedTrustDomains:
        cluster2:
          bundleEndpointProfile:
            endpointSPIFFEID: spiffe://cluster2.agntcy.org/spire/server
            type: https_spiffe
          bundleEndpointURL: https://spire-server-federation.cluster2.agntcy.org
          trustDomain: cluster2.agntcy.org

spiffe-oidc-discovery-provider:
  enabled: true
  tls:
    spire:
      enabled: false
  csiDriverName: csi.spiffe.io
  ingress:
    enabled: true

spire-agent:
  socketPath: /run/spire/sockets/spire-agent.sock

spiffe-csi-driver:
  pluginName: csi.spiffe.io
  agentSocketPath: /run/spire/sockets/spire-agent.sock
