# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

{{- include "chart.policies.validate" . }}
{{- if eq (include "chart.policies.enabled" .) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-policies
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  {{- range $name, $content := .Values.policies }}
  {{ $name }}: |
    {{- $content | nindent 4 }}
  {{- end }}
{{- end }}
