# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.secrets -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  {{- if .Values.secrets.privKey }}
  node.privkey: {{ .Values.secrets.privKey | b64enc }}
  {{- end }}
  {{- if or .Values.secrets.syncAuth.username .Values.secrets.syncAuth.password }}
  {{- $syncUsername := .Values.secrets.syncAuth.username | default "sync" }}
  {{- $syncPassword := .Values.secrets.syncAuth.password | default (randAlphaNum 32) }}
  sync-username: {{ $syncUsername | b64enc }}
  sync-password: {{ $syncPassword | b64enc }}
  {{- end }}
  {{- if or .Values.secrets.ociAuth.username .Values.secrets.ociAuth.password }}
  {{- $ociUsername := .Values.secrets.ociAuth.username | default "admin" }}
  {{- $ociPassword := .Values.secrets.ociAuth.password | default (randAlphaNum 32) }}
  oci-username: {{ $ociUsername | b64enc }}
  oci-password: {{ $ociPassword | b64enc }}
  {{- end }}
{{- end }}