// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: agntcy/dir/runtime/v1/discovery_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	DiscoveryService_ListProcesses_FullMethodName = "/agntcy.dir.runtime.v1.DiscoveryService/ListProcesses"
)

// DiscoveryServiceClient is the client API for DiscoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscoveryServiceClient interface {
	// List all record processes based on filters.
	ListProcesses(ctx context.Context, in *ListProcessesRequest, opts ...grpc.CallOption) (DiscoveryService_ListProcessesClient, error)
}

type discoveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoveryServiceClient(cc grpc.ClientConnInterface) DiscoveryServiceClient {
	return &discoveryServiceClient{cc}
}

func (c *discoveryServiceClient) ListProcesses(ctx context.Context, in *ListProcessesRequest, opts ...grpc.CallOption) (DiscoveryService_ListProcessesClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DiscoveryService_ServiceDesc.Streams[0], DiscoveryService_ListProcesses_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &discoveryServiceListProcessesClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DiscoveryService_ListProcessesClient interface {
	Recv() (*Process, error)
	grpc.ClientStream
}

type discoveryServiceListProcessesClient struct {
	grpc.ClientStream
}

func (x *discoveryServiceListProcessesClient) Recv() (*Process, error) {
	m := new(Process)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DiscoveryServiceServer is the server API for DiscoveryService service.
// All implementations should embed UnimplementedDiscoveryServiceServer
// for forward compatibility.
type DiscoveryServiceServer interface {
	// List all record processes based on filters.
	ListProcesses(*ListProcessesRequest, DiscoveryService_ListProcessesServer) error
}

// UnimplementedDiscoveryServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiscoveryServiceServer struct{}

func (UnimplementedDiscoveryServiceServer) ListProcesses(*ListProcessesRequest, DiscoveryService_ListProcessesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListProcesses not implemented")
}
func (UnimplementedDiscoveryServiceServer) testEmbeddedByValue() {}

// UnsafeDiscoveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoveryServiceServer will
// result in compilation errors.
type UnsafeDiscoveryServiceServer interface {
	mustEmbedUnimplementedDiscoveryServiceServer()
}

func RegisterDiscoveryServiceServer(s grpc.ServiceRegistrar, srv DiscoveryServiceServer) {
	// If the following call pancis, it indicates UnimplementedDiscoveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiscoveryService_ServiceDesc, srv)
}

func _DiscoveryService_ListProcesses_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListProcessesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DiscoveryServiceServer).ListProcesses(m, &discoveryServiceListProcessesServer{ServerStream: stream})
}

type DiscoveryService_ListProcessesServer interface {
	Send(*Process) error
	grpc.ServerStream
}

type discoveryServiceListProcessesServer struct {
	grpc.ServerStream
}

func (x *discoveryServiceListProcessesServer) Send(m *Process) error {
	return x.ServerStream.SendMsg(m)
}

// DiscoveryService_ServiceDesc is the grpc.ServiceDesc for DiscoveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscoveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agntcy.dir.runtime.v1.DiscoveryService",
	HandlerType: (*DiscoveryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListProcesses",
			Handler:       _DiscoveryService_ListProcesses_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agntcy/dir/runtime/v1/discovery_service.proto",
}
