# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: "3"

tasks:
  api:gen:
    desc: Generates API stubs
    dir: ./proto
    deps:
      - task: deps:protoc
      - task: deps:bufbuild
    # NOTE(ramizpolic): This allows Taskfile YAML parsing to accept '{' as a starting command token.
    # In translation, this is interpreted as a regular multi-line shell script.
    cmds:
      - "{{.BUFBUILD_BIN}} dep update"
      - for:
          matrix:
            TEMPLATE: ["buf.gen.runtime.yaml", "buf.gen.yaml"]
        cmd: |
          {{.BUFBUILD_BIN}} generate --template {{.ITEM.TEMPLATE}}
      - task: runtime:gen

  api:clean:
    desc: Clean generated API stubs
    deps:
      # Standard API
      - api:clean:go
      - api:clean:python
      - api:clean:javascript
      # Runtime API
      - api:clean:runtime:go

  api:clean:go:
    desc: Clean generated golang API stubs
    dir: ./api
    cmds:
      - find . \( -name "*.pb.go" \) -type f -delete

  api:clean:runtime:go:
    desc: Clean runtime generated golang API stubs
    dir: ./runtime
    cmds:
      - find . \( -name "*.pb.go" \) -type f -delete

  api:clean:python:
    desc: Clean generated Python API stubs
    dir: ./sdk/dir-py/agntcy
    cmd: rm -drf ./dir

  api:clean:javascript:
    desc: Clean generated JS/TS API stubs
    dir: ./sdk/dir-js/
    cmd: rm -drf ./api
