# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: Cron Jobs Management

on:
  schedule:
    - cron: "0 3 * * *" # Daily at 03:00 UTC
  workflow_dispatch:

permissions:
  packages: write
  contents: read
  actions: read
  issues: write
  security-events: write

jobs:
  build-images:
    name: Build Images
    uses: ./.github/workflows/reusable-build.yaml
    with:
      image_repo: ghcr.io/agntcy
      image_tag: main
      push: true

  nightly-scan:
    name: Container Security Scan (main)
    uses: ./.github/workflows/container-security-scan.yml
    needs:
      - build-images
    with:
      image-tag: main

  latest-scan:
    name: Container Security Scan (latest release)
    uses: ./.github/workflows/container-security-scan.yml
    needs:
      - build-images
