# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: Demo - DIR

on:
  workflow_dispatch:
    inputs:
      image_version:
        required: true
        type: string
        default: v1.2.0
        description: "dirctl version to use"
      server_addr:
        required: true
        type: string
        default: prod.gateway.ads.outshift.io:443
        description: "server address to use"

permissions:
  id-token: write
  contents: read

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup dirctl
        id: setup-dirctl
        uses: ./.github/actions/setup-dirctl
        with:
          version: ${{ inputs.image_version }}

      - name: Validate record
        uses: ./.github/actions/validate-record
        with:
          record_paths: tests/e2e/shared/testdata/record_100.json
          dirctl_path: ${{ steps.setup-dirctl.outputs.dirctl_path }}

      - name: Fetch GitHub OIDC token
        id: oidc
        uses: ./.github/actions/fetch-oidc-token
        with:
          audience: dir

      - name: Push record
        id: push
        uses: ./.github/actions/push-record
        with:
          record_paths: tests/e2e/shared/testdata/record_100.json
          server_addr: ${{ inputs.server_addr }}
          auth_token: ${{ steps.oidc.outputs.token }}
          dirctl_path: ${{ steps.setup-dirctl.outputs.dirctl_path }}

      - name: Sign record (OIDC)
        uses: ./.github/actions/sign-record
        with:
          cids: ${{ steps.push.outputs.cids }}
          oidc_client_id: https://github.com/${{ github.repository }}/.github/workflows/demo-dir.yaml@${{ github.ref }}
          server_addr: ${{ inputs.server_addr }}
          auth_token: ${{ steps.oidc.outputs.token }}
          dirctl_path: ${{ steps.setup-dirctl.outputs.dirctl_path }}

      - name: Publish record
        uses: ./.github/actions/publish-record
        with:
          cids: ${{ steps.push.outputs.cids }}
          server_addr: ${{ inputs.server_addr }}
          auth_token: ${{ steps.oidc.outputs.token }}
          dirctl_path: ${{ steps.setup-dirctl.outputs.dirctl_path }}

      - name: Search for record
        env:
          SERVER_ADDR: ${{ inputs.server_addr }}
          AUTH_TOKEN: ${{ steps.oidc.outputs.token }}
          DIRCTL_PATH: ${{ steps.setup-dirctl.outputs.dirctl_path }}
        run: |
          "${DIRCTL_PATH}" search --name "burger_seller_agent" --server-addr="$SERVER_ADDR" --auth-mode=oidc "--auth-token=$AUTH_TOKEN"

      - name: Verify record
        env:
          SERVER_ADDR: ${{ inputs.server_addr }}
          AUTH_TOKEN: ${{ steps.oidc.outputs.token }}
          DIRCTL_PATH: ${{ steps.setup-dirctl.outputs.dirctl_path }}
        run: |
          CID=$(echo '${{ steps.push.outputs.cids }}' | jq -r '.[]')
          "${DIRCTL_PATH}" verify "$CID" --server-addr="$SERVER_ADDR" --auth-mode=oidc "--auth-token=$AUTH_TOKEN"
