# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: Dir - Local Demo on Windows

description: |
  This workflow demonstrates how to use the Dir CLI on Windows.
  It includes steps for compiling the CLI, building an agent, and verifying the binary.

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: windows-latest
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create bin directory
        run: |
          echo "Creating bin directory"
          mkdir bin

      # TODO Replace with curl once windows binary is available with release
      - name: Compile
        run: |
          echo "Compiling CLI"
          task cli:compile

      - name: Verify dirctl binary
        run: |
          if (Test-Path .\bin\dirctl.exe) {
            echo "dirctl binary exists"
          } else {
            echo "dirctl binary is missing"
            exit 1
          }

      - name: Run version command on windows
        run: |
          echo "Running version command"
          .\bin\dirctl.exe version

      - name: Run build command
        run: |
          echo "Running dir build command"
          .\bin\dirctl.exe build e2e/testdata > agent.json
          echo "Built agent.json:"
          cat agent.json

      # TODO Start server and run push/publish commands
