name: Lint and comment PR Title

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50
        id: lint_pr_title
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          ignoreLabels: |
            ignore-semantic-pr
          subjectPattern: '^(?![A-Z]).+$'
          types: |
            build
            chore
            ci
            deps
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
            release
          scopes: |
            dir
            dir/api
            dir/server
            dir/client
            sdk
            sdk/go
            sdk/js
            sdk/py
            cli
            cli/dir
            cli/hub
            helm
            helm/dir
            helm/dirctl
            docker
            .*
          requireScope: true

      - uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: "Hey there and thank you for opening this pull request! \U0001F44B\U0001F3FC\n\nWe require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/),\nand it looks like your proposed title needs to be adjusted.\n\nDetails:\n\n```\n${{ steps.lint_pr_title.outputs.error_message }}\n```\n\nExamples:\n\n```\n- feat(dir/api): add new authentication endpoint\n- fix(sdk/js): resolve issue with token refresh\n- chore(deps): update dependencies\n```\n"

      - if: '${{ steps.lint_pr_title.outputs.error_message == null }}'
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405
        with:
          header: pr-title-lint-error
          delete: true
