# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: Release Helm

on:
  workflow_dispatch:
    inputs:
      image_repo:
        required: true
        type: string
        description: "Image repo to use."
        default: "ghcr.io/agntcy"
      release_tag:
        required: true
        type: string
        description: "Release tag for all components."
  workflow_call:
    inputs:
      image_repo:
        required: true
        type: string
        description: "Image repo to use."
      release_tag:
        required: true
        type: string
        description: "Release tag for all components."
      chart_path:
        required: false
        type: string
        description: "Chart path component (e.g., 'dir' or 'dir-dev'). Defaults to 'dir'."
        default: "dir"

jobs:
  chart:
    name: Helm chart
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - chart: dir
            source_path: install/charts/dir
          - chart: dirctl
            source_path: install/charts/dirctl
          - chart: runtime
            source_path: runtime/install/chart
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: notused
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Setup Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0

      - name: Helm update nested dependencies
        if: matrix.chart == 'dir'
        shell: bash
        run: helm dependency update ${{ matrix.source_path }}/apiserver

      - name: Helm update
        shell: bash
        run: helm dependency update ${{ matrix.source_path }}

      - name: Helm lint
        shell: bash
        run: helm lint ${{ matrix.source_path }} --with-subcharts

      - name: Helm package
        id: build
        shell: bash
        run: |
          helm package ${{ matrix.source_path }} --dependency-update --version ${{ inputs.release_tag }}
          echo "package=${{ matrix.chart }}-${{ inputs.release_tag }}.tgz" >> "$GITHUB_OUTPUT"

      - name: Helm push to GHCR OCI registry
        shell: bash
        run: |
          CHART_PATH="${{ inputs.chart_path || 'dir' }}/helm-charts"
          echo "🚧 Pushing ${{ steps.build.outputs.package }} to GHCR OCI registry"
          echo "Chart path: ${CHART_PATH}"
          helm push ${{ steps.build.outputs.package }} oci://${{ inputs.image_repo }}/${CHART_PATH}
